import {
  ArchiveIcon,
  AudioWaveformIcon,
  BadgeCheckIcon,
  BookOpenIcon,
  BrainCircuitIcon,
  ChartLineIcon,
  ClapperboardIcon,
  CpuIcon,
  DatabaseIcon,
  FileStackIcon,
  FileTextIcon,
  GraduationCapIcon,
  ImageIcon,
  KanbanIcon,
  LibraryIcon,
  ListChecksIcon,
  type LucideIcon,
  NetworkIcon,
  PenToolIcon,
  PresentationIcon,
  RadioIcon,
  SatelliteIcon,
  SearchIcon,
  ShieldIcon,
  SigmaIcon,
  SparklesIcon,
  TerminalIcon,
} from "lucide-react";
import type { COURSE_CARD_COLORS } from "@/config/courses";
import type {
  ResourceCategoryId,
  ResourceGroupId,
} from "@/lib/resources/types";

export interface ResourceCategory {
  color: (typeof COURSE_CARD_COLORS)[number];
  group: ResourceGroupId;
  icon: LucideIcon;
  id: ResourceCategoryId;
  label: string;
  /** One line under the section heading. */
  tagline: string;
}

export const RESOURCE_CATEGORIES: ResourceCategory[] = [
  {
    color: "chart-1",
    group: "everyday",
    icon: SparklesIcon,
    id: "ai-assistants",
    label: "AI assistants",
    tagline: "Explain a derivation, summarise slides, draft a first pass.",
  },
  {
    color: "chart-2",
    group: "everyday",
    icon: FileStackIcon,
    id: "file-utilities",
    label: "PDF, image, and media utilities",
    tagline: "Merge, compress, convert, and clean up files.",
  },
  {
    color: "chart-3",
    group: "everyday",
    icon: PenToolIcon,
    id: "diagramming",
    label: "Diagrams and figures",
    tagline: "Sketch a topology, draw a block diagram, export a vector figure.",
  },
  {
    color: "chart-4",
    group: "everyday",
    icon: PresentationIcon,
    id: "presentations",
    label: "Presentations and slides",
    tagline: "Build a deck by hand, from Markdown, or from a prompt.",
  },
  {
    color: "chart-4",
    group: "everyday",
    icon: KanbanIcon,
    id: "productivity",
    label: "Notes and project tracking",
    tagline: "Keep the semester and the thesis on a board.",
  },
  {
    color: "chart-5",
    group: "everyday",
    icon: TerminalIcon,
    id: "dev",
    label: "Development environments",
    tagline: "Editors, version control, containers, and package managers.",
  },
  {
    color: "chart-1",
    group: "everyday",
    icon: BookOpenIcon,
    id: "learning",
    label: "Learning and study aids",
    tagline: "Courses, flashcards, and references outside the syllabus.",
  },
  {
    color: "chart-2",
    group: "coursework",
    icon: SigmaIcon,
    id: "math",
    label: "Math and symbolic computation",
    tagline: "Check a transform, solve a system, plot a function.",
  },
  {
    color: "chart-3",
    group: "coursework",
    icon: ChartLineIcon,
    id: "data-analysis",
    label: "Statistics and notebooks",
    tagline: "Numbers, tests, and figures that survive a defense.",
  },
  {
    color: "chart-4",
    group: "coursework",
    icon: AudioWaveformIcon,
    id: "dsp",
    label: "Signal processing and SDR",
    tagline: "Filters, spectra, and software radio chains.",
  },
  {
    color: "chart-5",
    group: "coursework",
    icon: RadioIcon,
    id: "wireless",
    label: "Communications and wireless",
    tagline: "Modulation, coding, channels, and 5G stacks.",
  },
  {
    color: "chart-1",
    group: "coursework",
    icon: SatelliteIcon,
    id: "satellite",
    label: "Satellite and space",
    tagline: "Passes, link budgets, and telemetry decoding.",
  },
  {
    color: "chart-2",
    group: "coursework",
    icon: NetworkIcon,
    id: "networking",
    label: "Networking",
    tagline: "Packets, topologies, routing, and measurement.",
  },
  {
    color: "chart-3",
    group: "coursework",
    icon: ClapperboardIcon,
    id: "multimedia",
    label: "Multimedia and streaming",
    tagline: "Codecs, packaging, playback, and quality metrics.",
  },
  {
    color: "chart-4",
    group: "coursework",
    icon: BrainCircuitIcon,
    id: "ml",
    label: "Machine learning",
    tagline: "Training, compute, tracking, and datasets.",
  },
  {
    color: "chart-5",
    group: "coursework",
    icon: DatabaseIcon,
    id: "data-mining",
    label: "Data mining",
    tagline: "Dataframes, mining workbenches, and profiling.",
  },
  {
    color: "chart-1",
    group: "coursework",
    icon: ImageIcon,
    id: "vision",
    label: "Image processing and vision",
    tagline: "Annotation, augmentation, and detection.",
  },
  {
    color: "chart-2",
    group: "coursework",
    icon: ShieldIcon,
    id: "security",
    label: "Security and cryptography",
    tagline: "Primitives, practice ranges, and monitoring.",
  },
  {
    color: "chart-3",
    group: "coursework",
    icon: CpuIcon,
    id: "embedded",
    label: "Embedded systems",
    tagline: "Toolchains, RTOS, simulators, and debug.",
  },
  {
    color: "chart-4",
    group: "research",
    icon: SearchIcon,
    id: "literature",
    label: "Literature search and discovery",
    tagline: "Databases, citation graphs, and reading aids.",
  },
  {
    color: "chart-5",
    group: "research",
    icon: LibraryIcon,
    id: "references",
    label: "Reference management",
    tagline: "Collect, cite, and keep DOIs clean.",
  },
  {
    color: "chart-1",
    group: "research",
    icon: FileTextIcon,
    id: "writing",
    label: "Writing and typesetting",
    tagline: "LaTeX, Typst, Quarto, and proofing.",
  },
  {
    color: "chart-2",
    group: "research",
    icon: ListChecksIcon,
    id: "review",
    label: "Systematic review",
    tagline: "Screening, snowballing, and PRISMA reporting.",
  },
  {
    color: "chart-3",
    group: "research",
    icon: ArchiveIcon,
    id: "thesis-archives",
    label: "Open access and thesis archives",
    tagline: "Prior theses and open full text.",
  },
  {
    color: "chart-4",
    group: "research",
    icon: BadgeCheckIcon,
    id: "integrity-archiving",
    label: "Integrity and archiving",
    tagline: "Similarity checks, DOIs for artifacts, identifiers.",
  },
  {
    color: "chart-5",
    group: "access",
    icon: GraduationCapIcon,
    id: "access",
    label: "Student and university programs",
    tagline: "Bundles and campus licenses to check before paying.",
  },
];

export const RESOURCE_CATEGORY_BY_ID: ReadonlyMap<
  ResourceCategoryId,
  ResourceCategory
> = new Map(RESOURCE_CATEGORIES.map((category) => [category.id, category]));
