import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const ACCESS: Resource[] = [
  {
    access: "student",
    brandIcon: "GitHub",
    category: "access",
    description: "Copilot, JetBrains, cloud credits, and more while enrolled.",
    featured: true,
    id: "github-student-pack",
    isOpenSource: false,
    name: "GitHub Student Developer Pack",
    platform: ["web"],
    requiresAccount: true,
    tags: ["bundle", "student"],
    url: "https://education.github.com/pack",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    brandIcon: "Microsoft Azure",
    category: "access",
    description: "Annual credit without a card.",
    id: "azure-for-students",
    isOpenSource: false,
    name: "Microsoft Azure for Students",
    platform: ["web"],
    requiresAccount: true,
    tags: ["cloud", "credits"],
    url: "https://azure.microsoft.com/en-us/free/students",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    brandIcon: "Amazon Web Services",
    category: "access",
    description: "Guided cloud labs and credits.",
    id: "aws-educate",
    isOpenSource: false,
    name: "AWS Educate",
    platform: ["web"],
    requiresAccount: true,
    tags: ["cloud", "credits"],
    url: "https://aws.amazon.com/education/awseducate",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Google Cloud",
    category: "access",
    description: "Skill paths and lab credits.",
    id: "google-cloud-skills-boost",
    isOpenSource: false,
    name: "Google Cloud Skills Boost",
    platform: ["web"],
    requiresAccount: true,
    tags: ["cloud", "courses"],
    url: "https://www.cloudskillsboost.google",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    brandIcon: "Microsoft Office",
    category: "access",
    description: "Word, Excel, PowerPoint under the university account.",
    id: "microsoft-365-education",
    isOpenSource: false,
    name: "Microsoft 365 Education",
    platform: ["web"],
    requiresAccount: true,
    tags: ["office"],
    url: "https://www.microsoft.com/education/products/office",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    brandIcon: "Notion",
    category: "access",
    description: "Free Plus plan with an academic email.",
    id: "notion-for-education",
    isOpenSource: false,
    name: "Notion for Education",
    platform: ["web"],
    requiresAccount: true,
    tags: ["notes"],
    url: "https://www.notion.so/product/notion-for-education",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    brandIcon: "Figma",
    category: "access",
    description: "Professional design tools free for students.",
    id: "figma-for-education",
    isOpenSource: false,
    name: "Figma for Education",
    platform: ["web"],
    requiresAccount: true,
    tags: ["design"],
    url: "https://www.figma.com/education",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    category: "access",
    description: "Engineering and design software for students.",
    id: "autodesk-education",
    isOpenSource: false,
    name: "Autodesk Education",
    platform: ["web"],
    requiresAccount: true,
    tags: ["cad", "design"],
    url: "https://www.autodesk.com/education",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    category: "access",
    description: "Student rate for journals and conferences.",
    id: "ieee-student-membership",
    isOpenSource: false,
    name: "IEEE student membership",
    platform: ["web"],
    requiresAccount: true,
    tags: ["membership"],
    url: "https://www.ieee.org/membership/student.html",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
