import { AI_PRIVACY_NOTE } from "@/config/resources/copy";
import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const AI_ASSISTANTS: Resource[] = [
  {
    access: "freemium",
    brandIcon: "Claude AI",
    category: "ai-assistants",
    description: "Long-context reading and step-by-step derivations.",
    featured: true,
    id: "claude",
    isOpenSource: false,
    name: "Claude",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["assistant", "llm"],
    thesisStages: ["screen"],
    url: "https://claude.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    aliases: ["OpenAI"],
    brandIcon: "OpenAI",
    category: "ai-assistants",
    description: "General assistant with the largest plugin ecosystem.",
    featured: true,
    id: "chatgpt",
    isOpenSource: false,
    name: "ChatGPT",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["assistant", "llm"],
    thesisStages: ["screen"],
    url: "https://chatgpt.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Gemini",
    category: "ai-assistants",
    description:
      "Ties into Drive and Docs, where course material already lives.",
    id: "gemini",
    isOpenSource: false,
    name: "Google Gemini",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["assistant", "llm"],
    thesisStages: ["screen"],
    url: "https://gemini.google.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ai-assistants",
    description: "Answers only from the PDFs and slides you upload.",
    featured: true,
    id: "notebooklm",
    isOpenSource: false,
    name: "NotebookLM",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["assistant", "llm", "summary"],
    thesisStages: ["screen"],
    url: "https://notebooklm.google.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Perplexity AI",
    category: "ai-assistants",
    description: "Web answers with inline citations for quick grounding.",
    id: "perplexity",
    isOpenSource: false,
    name: "Perplexity",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["assistant", "search"],
    thesisStages: ["search"],
    url: "https://www.perplexity.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Microsoft Copilot",
    category: "ai-assistants",
    description: "Bundled with a Microsoft account, no extra signup.",
    id: "microsoft-copilot",
    isOpenSource: false,
    name: "Microsoft Copilot",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["assistant", "llm"],
    url: "https://copilot.microsoft.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
