import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const DATA_MINING: Resource[] = [
  {
    access: "free",
    category: "data-mining",
    description: "Visual workflows for exploratory mining without code.",
    featured: true,
    id: "orange",
    isOpenSource: true,
    name: "Orange",
    platform: ["desktop"],
    tags: ["workflow", "gui"],
    url: "https://orangedatamining.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "Classic workbench with a deep algorithm collection.",
    id: "weka",
    isOpenSource: true,
    name: "Weka",
    platform: ["desktop"],
    tags: ["workbench", "java"],
    url: "https://ml.cms.waikato.ac.nz/weka",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Polars",
    category: "data-mining",
    description: "Rust dataframe that handles larger-than-memory work.",
    featured: true,
    id: "polars",
    isOpenSource: true,
    name: "Polars",
    platform: ["library"],
    tags: ["dataframe", "python"],
    url: "https://pola.rs",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "In-process SQL over CSV and Parquet.",
    featured: true,
    id: "duckdb",
    isOpenSource: true,
    name: "DuckDB",
    platform: ["library"],
    tags: ["sql", "analytics"],
    url: "https://duckdb.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "Parallel pandas and NumPy for datasets beyond RAM.",
    id: "dask",
    isOpenSource: true,
    name: "Dask",
    platform: ["library"],
    tags: ["dataframe", "parallel"],
    url: "https://www.dask.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["PySpark"],
    category: "data-mining",
    description: "Distributed mining when one machine is not enough.",
    id: "apache-spark",
    isOpenSource: true,
    name: "Apache Spark",
    platform: ["library"],
    tags: ["distributed", "big data"],
    url: "https://spark.apache.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "Frequent itemsets, association rules, and stacking.",
    id: "mlxtend",
    isOpenSource: true,
    name: "mlxtend",
    platform: ["library"],
    tags: ["association rules", "python"],
    url: "https://rasbt.github.io/mlxtend",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "Low-code model comparison.",
    id: "pycaret",
    isOpenSource: true,
    name: "PyCaret",
    platform: ["library"],
    tags: ["low-code", "python"],
    url: "https://pycaret.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "One-line dataset profiling reports.",
    id: "ydata-profiling",
    isOpenSource: true,
    name: "ydata-profiling",
    platform: ["library"],
    tags: ["profiling", "python"],
    url: "https://github.com/ydataai/ydata-profiling",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "Data quality assertions for a pipeline.",
    id: "great-expectations",
    isOpenSource: true,
    name: "Great Expectations",
    platform: ["library"],
    tags: ["data quality"],
    url: "https://greatexpectations.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "Clustering and outlier detection toolkit.",
    id: "elki",
    isOpenSource: true,
    name: "ELKI",
    platform: ["desktop"],
    tags: ["clustering", "outliers", "java"],
    url: "https://elki-project.github.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-mining",
    description: "Columnar format under Polars, DuckDB, and pandas interop.",
    id: "apache-arrow",
    isOpenSource: true,
    name: "Apache Arrow",
    platform: ["library"],
    tags: ["columnar", "format"],
    url: "https://arrow.apache.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
