import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const DATA_ANALYSIS: Resource[] = [
  {
    access: "free",
    aliases: ["Jupyter"],
    category: "data-analysis",
    description: "Notebooks that double as reproducible thesis appendices.",
    featured: true,
    id: "jupyter",
    isOpenSource: true,
    name: "JupyterLab",
    platform: ["desktop", "web"],
    tags: ["notebook", "python"],
    thesisStages: ["experiment", "analyse"],
    url: "https://jupyter.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "Arrays and linear algebra under every Python stack.",
    id: "numpy",
    isOpenSource: true,
    name: "NumPy",
    platform: ["library"],
    tags: ["python", "numerical"],
    thesisStages: ["analyse"],
    url: "https://numpy.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["scipy.signal"],
    category: "data-analysis",
    description:
      "Optimisation, statistics, and signal routines. scipy.signal covers filter design.",
    featured: true,
    id: "scipy",
    isOpenSource: true,
    name: "SciPy",
    platform: ["library"],
    tags: ["python", "signal", "statistics"],
    thesisStages: ["analyse"],
    url: "https://scipy.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "Tabular cleaning and result tables.",
    featured: true,
    id: "pandas",
    isOpenSource: true,
    name: "pandas",
    platform: ["library"],
    tags: ["python", "dataframe"],
    thesisStages: ["analyse"],
    url: "https://pandas.pydata.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "Vector plots that match the document font.",
    featured: true,
    id: "matplotlib",
    isOpenSource: true,
    name: "Matplotlib",
    platform: ["library"],
    tags: ["python", "plot", "figure"],
    thesisStages: ["analyse"],
    url: "https://matplotlib.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "Statistical plots with confidence bands.",
    id: "seaborn",
    isOpenSource: true,
    name: "seaborn",
    platform: ["library"],
    tags: ["python", "plot"],
    thesisStages: ["analyse"],
    url: "https://seaborn.pydata.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "Interactive figures for exploration.",
    id: "plotly",
    isOpenSource: true,
    name: "Plotly",
    platform: ["library"],
    tags: ["python", "plot"],
    url: "https://plotly.com/python",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["RStudio", "Posit"],
    brandIcon: "R",
    category: "data-analysis",
    description: "Statistics and publication plots outside the Python path.",
    featured: true,
    id: "r-rstudio",
    isOpenSource: true,
    name: "R and RStudio",
    platform: ["desktop"],
    tags: ["statistics", "plot"],
    thesisStages: ["analyse"],
    url: "https://posit.co/products/open-source/rstudio",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "Point-and-click Bayesian and frequentist statistics.",
    featured: true,
    id: "jasp",
    isOpenSource: true,
    name: "JASP",
    platform: ["desktop"],
    tags: ["statistics", "gui"],
    thesisStages: ["analyse"],
    url: "https://jasp-stats.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "GUI statistics with an R syntax bridge.",
    id: "jamovi",
    isOpenSource: true,
    name: "jamovi",
    platform: ["desktop"],
    tags: ["statistics", "gui"],
    thesisStages: ["analyse"],
    url: "https://www.jamovi.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "SPSS-compatible free alternative.",
    id: "pspp",
    isOpenSource: true,
    name: "PSPP",
    platform: ["desktop"],
    tags: ["statistics", "spss"],
    url: "https://www.gnu.org/software/pspp",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description:
      "Regression, hypothesis tests, and multiple-comparison correction.",
    id: "statsmodels",
    isOpenSource: true,
    name: "statsmodels",
    platform: ["library"],
    tags: ["python", "statistics"],
    thesisStages: ["analyse"],
    url: "https://www.statsmodels.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "Statistical tests with effect sizes in one call.",
    id: "pingouin",
    isOpenSource: true,
    name: "Pingouin",
    platform: ["library"],
    tags: ["python", "statistics"],
    thesisStages: ["analyse"],
    url: "https://pingouin-stats.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "data-analysis",
    description: "Visual analytics workflows without code.",
    id: "knime",
    isOpenSource: false,
    name: "KNIME",
    platform: ["desktop"],
    requiresAccount: true,
    tags: ["workflow", "gui"],
    url: "https://www.knime.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "data-analysis",
    description: "Structured data to custom charts without code.",
    id: "rawgraphs",
    isOpenSource: true,
    name: "RAWGraphs",
    platform: ["web"],
    tags: ["plot"],
    url: "https://www.rawgraphs.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "data-analysis",
    description: "Browser notebooks for interactive visualisation.",
    id: "observable",
    isOpenSource: false,
    name: "Observable",
    platform: ["web"],
    requiresAccount: true,
    tags: ["notebook", "plot"],
    url: "https://observablehq.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
