import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const DEV: Resource[] = [
  {
    access: "free",
    aliases: ["VS Code"],
    brandIcon: "Visual Studio Code",
    category: "dev",
    description: "The editor across every course with a coding component.",
    featured: true,
    id: "vs-code",
    isOpenSource: true,
    name: "Visual Studio Code",
    platform: ["desktop"],
    tags: ["editor"],
    thesisStages: ["experiment"],
    url: "https://code.visualstudio.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "GitHub",
    category: "dev",
    description:
      "Version control, code review, and hosting for course and thesis code.",
    featured: true,
    id: "github",
    isOpenSource: false,
    name: "GitHub",
    platform: ["web"],
    requiresAccount: true,
    tags: ["git", "hosting"],
    thesisStages: ["experiment"],
    url: "https://github.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "GitHub",
    category: "dev",
    description:
      "Browser VS Code with cloud compute. More hours with the Student Pack.",
    id: "github-codespaces",
    isOpenSource: false,
    name: "GitHub Codespaces",
    platform: ["web"],
    requiresAccount: true,
    tags: ["cloud", "editor"],
    url: "https://github.com/features/codespaces",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "GitLab",
    category: "dev",
    description: "Git hosting with built-in CI.",
    id: "gitlab",
    isOpenSource: false,
    name: "GitLab",
    platform: ["web"],
    requiresAccount: true,
    tags: ["git", "hosting", "ci"],
    url: "https://gitlab.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Replit",
    category: "dev",
    description: "Browser coding with zero setup.",
    id: "replit",
    isOpenSource: false,
    name: "Replit",
    platform: ["web"],
    requiresAccount: true,
    tags: ["editor", "cloud"],
    url: "https://replit.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    aliases: ["PyCharm", "IntelliJ", "CLion"],
    brandIcon: "JetBrains",
    category: "dev",
    description: "PyCharm, IntelliJ, CLion. Free while enrolled.",
    id: "jetbrains-ides",
    isOpenSource: false,
    name: "JetBrains IDEs",
    platform: ["desktop"],
    requiresAccount: true,
    tags: ["editor", "ide"],
    url: "https://www.jetbrains.com/community/education",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Docker",
    category: "dev",
    description:
      "Reproducible environments that pin the toolchain. Desktop is free for education.",
    featured: true,
    id: "docker",
    isOpenSource: true,
    name: "Docker",
    platform: ["desktop", "cli"],
    tags: ["containers", "reproducibility"],
    thesisStages: ["experiment"],
    url: "https://www.docker.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Git",
    category: "dev",
    description: "Version control itself.",
    id: "git",
    isOpenSource: true,
    name: "Git",
    platform: ["cli"],
    tags: ["git"],
    url: "https://git-scm.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Mamba", "conda"],
    category: "dev",
    description:
      "Conda-compatible Python environments without licensing strings.",
    id: "miniforge",
    isOpenSource: true,
    name: "Miniforge and Mamba",
    platform: ["cli"],
    tags: ["python", "environment"],
    thesisStages: ["experiment"],
    url: "https://github.com/conda-forge/miniforge",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Stack Overflow",
    category: "dev",
    description: "Programming questions and answers.",
    id: "stack-overflow",
    isOpenSource: false,
    name: "Stack Overflow",
    platform: ["web"],
    tags: ["reference"],
    url: "https://stackoverflow.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["MDN"],
    category: "dev",
    description: "Web platform reference.",
    id: "mdn-web-docs",
    isOpenSource: true,
    name: "MDN Web Docs",
    platform: ["web"],
    tags: ["reference", "web"],
    url: "https://developer.mozilla.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dev",
    description: "Searchable offline documentation for many languages.",
    id: "devdocs",
    isOpenSource: true,
    name: "DevDocs",
    platform: ["web"],
    tags: ["reference"],
    url: "https://devdocs.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "GitHub",
    category: "dev",
    description: "Beginner-friendly Git client.",
    id: "github-desktop",
    isOpenSource: true,
    name: "GitHub Desktop",
    platform: ["desktop"],
    tags: ["git"],
    url: "https://github.com/apps/desktop",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Neovim",
    category: "dev",
    description: "Modal editor for terminal-first work.",
    id: "neovim",
    isOpenSource: true,
    name: "Neovim",
    platform: ["cli"],
    tags: ["editor"],
    url: "https://neovim.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
