import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const DIAGRAMMING: Resource[] = [
  {
    access: "free",
    category: "diagramming",
    description: "Hand-drawn style sketches for system and network diagrams.",
    featured: true,
    id: "excalidraw",
    isOpenSource: true,
    name: "Excalidraw",
    platform: ["web"],
    tags: ["diagramming", "whiteboard", "flowchart"],
    url: "https://excalidraw.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Mermaid"],
    brandIcon: "Mermaid",
    category: "diagramming",
    description: "Flowcharts, sequence diagrams, and Gantt charts from text.",
    featured: true,
    id: "mermaid-live",
    isOpenSource: true,
    name: "Mermaid Live Editor",
    platform: ["web"],
    tags: ["diagramming", "flowchart", "gantt"],
    thesisStages: ["defend"],
    url: "https://mermaid.live",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["draw.io"],
    category: "diagramming",
    description: "Full stencil sets for network and architecture diagrams.",
    featured: true,
    id: "diagrams-net",
    isOpenSource: true,
    name: "diagrams.net",
    platform: ["web", "desktop"],
    tags: ["diagramming", "flowchart", "network"],
    url: "https://app.diagrams.net",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "diagramming",
    description: "Infinite canvas whiteboard with live collaboration.",
    id: "tldraw",
    isOpenSource: true,
    name: "tldraw",
    platform: ["web"],
    tags: ["whiteboard", "canvas"],
    url: "https://www.tldraw.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "diagramming",
    description: "UML, component, and Gantt diagrams from text.",
    id: "plantuml",
    isOpenSource: true,
    name: "PlantUML",
    platform: ["web", "cli"],
    tags: ["diagramming", "uml", "gantt"],
    url: "https://plantuml.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "diagramming",
    description: "Polished diagrams, education plans available.",
    id: "lucidchart",
    isOpenSource: false,
    name: "Lucidchart",
    platform: ["web"],
    requiresAccount: true,
    tags: ["diagramming"],
    url: "https://www.lucidchart.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "diagramming",
    description: "Vector editor for publication figures and block diagrams.",
    featured: true,
    id: "inkscape",
    isOpenSource: true,
    name: "Inkscape",
    platform: ["desktop"],
    tags: ["vector", "figure"],
    thesisStages: ["analyse"],
    url: "https://inkscape.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "diagramming",
    description: "Graph and topology figures from a DOT description.",
    id: "graphviz",
    isOpenSource: true,
    name: "Graphviz",
    platform: ["cli"],
    tags: ["graph", "figure"],
    thesisStages: ["analyse"],
    url: "https://graphviz.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["TikZ"],
    category: "diagramming",
    description: "Plots and diagrams compiled inside LaTeX.",
    id: "pgfplots-tikz",
    isOpenSource: true,
    name: "PGFPlots and TikZ",
    platform: ["library"],
    tags: ["latex", "figure", "plot"],
    thesisStages: ["analyse"],
    url: "https://pgfplots.sourceforge.net",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "diagramming",
    description: "Online whiteboard for group planning.",
    id: "miro",
    isOpenSource: false,
    name: "Miro",
    platform: ["web"],
    requiresAccount: true,
    tags: ["whiteboard"],
    url: "https://miro.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    aliases: ["FigJam"],
    brandIcon: "Figma",
    category: "diagramming",
    description:
      "Interface design and collaborative diagrams. Free for education.",
    id: "figma",
    isOpenSource: false,
    name: "Figma and FigJam",
    platform: ["web"],
    requiresAccount: true,
    tags: ["design", "whiteboard"],
    url: "https://www.figma.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Canva",
    category: "diagramming",
    description: "Slides, posters, and simple figures.",
    id: "canva",
    isOpenSource: false,
    name: "Canva",
    platform: ["web"],
    requiresAccount: true,
    tags: ["slides", "deck", "design"],
    thesisStages: ["defend"],
    url: "https://www.canva.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Google Slides",
    category: "diagramming",
    description: "Collaborative presentations.",
    id: "google-slides",
    isOpenSource: false,
    name: "Google Slides",
    platform: ["web"],
    requiresAccount: true,
    tags: ["slides", "deck", "presentation"],
    thesisStages: ["defend"],
    url: "https://slides.google.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
