import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const DSP: Resource[] = [
  {
    access: "free",
    category: "dsp",
    description:
      "Flow-graph SDR framework for modulation and demodulation chains.",
    featured: true,
    id: "gnu-radio",
    isOpenSource: true,
    name: "GNU Radio",
    platform: ["desktop"],
    tags: ["sdr", "radio", "signal"],
    thesisStages: ["experiment"],
    url: "https://www.gnuradio.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "Free textbook with runnable Python for SDR and RF basics.",
    featured: true,
    id: "pysdr",
    isOpenSource: false,
    name: "PySDR",
    platform: ["reference"],
    tags: ["sdr", "textbook", "python"],
    url: "https://pysdr.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "Filter design and transforms with MATLAB-compatible calls.",
    id: "octave-signal",
    isOpenSource: true,
    name: "Octave signal package",
    platform: ["library"],
    tags: ["filter", "octave"],
    url: "https://gnu-octave.github.io/packages/signal",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "C DSP library small enough to read, built for embedded SDR.",
    featured: true,
    id: "liquid-dsp",
    isOpenSource: true,
    name: "liquid-dsp",
    platform: ["library"],
    tags: ["sdr", "embedded", "c"],
    url: "https://liquidsdr.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "Inspect captures and identify unknown transmissions.",
    id: "sigdigger",
    isOpenSource: true,
    name: "SigDigger",
    platform: ["desktop"],
    tags: ["sdr", "analyser"],
    url: "https://github.com/BatchDrake/SigDigger",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["SDRPlusPlus"],
    category: "dsp",
    description:
      "Light receiver app for browsing spectrum with cheap hardware.",
    id: "sdrpp",
    isOpenSource: true,
    name: "SDR++",
    platform: ["desktop"],
    tags: ["sdr", "receiver"],
    url: "https://www.sdrpp.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "Feature-rich SDR application with transmit support.",
    id: "sdrangel",
    isOpenSource: true,
    name: "SDRangel",
    platform: ["desktop"],
    tags: ["sdr", "receiver"],
    url: "https://www.sdrangel.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "Visual inspection of recorded IQ captures.",
    id: "inspectrum",
    isOpenSource: true,
    name: "inspectrum",
    platform: ["desktop"],
    tags: ["sdr", "analyser"],
    url: "https://github.com/miek/inspectrum",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "GNU Radio source and sink blocks for low-cost SDR hardware.",
    id: "gr-osmosdr",
    isOpenSource: true,
    name: "gr-osmosdr",
    platform: ["library"],
    tags: ["sdr", "hardware"],
    url: "https://osmocom.org/projects/gr-osmosdr",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "The cheapest receive-only hardware path into the course.",
    id: "rtl-sdr-quick-start",
    isOpenSource: false,
    name: "RTL-SDR quick start",
    note: "Needs an RTL-SDR dongle.",
    platform: ["reference"],
    tags: ["sdr", "hardware", "guide"],
    url: "https://www.rtl-sdr.com/rtl-sdr-quick-start-guide",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "Spectrogram view for checking a filter output.",
    id: "audacity",
    isOpenSource: true,
    name: "Audacity",
    platform: ["desktop"],
    tags: ["audio", "spectrogram"],
    url: "https://www.audacityteam.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "Layered audio analysis with spectrogram and pitch.",
    id: "sonic-visualiser",
    isOpenSource: true,
    name: "Sonic Visualiser",
    platform: ["desktop"],
    tags: ["audio", "spectrogram"],
    url: "https://www.sonicvisualiser.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description:
      "Browser FIR designer that plots impulse and frequency responses.",
    id: "tfilter",
    isOpenSource: false,
    name: "TFilter",
    platform: ["web"],
    tags: ["filter", "fir"],
    url: "http://t-filter.engineerjs.com",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description: "STFT, mel spectrograms, and audio features.",
    id: "librosa",
    isOpenSource: true,
    name: "librosa",
    platform: ["library"],
    tags: ["audio", "python"],
    url: "https://librosa.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "dsp",
    description:
      "ARM's optimised DSP library, the bridge from EENG527 to embedded.",
    id: "cmsis-dsp",
    isOpenSource: true,
    name: "CMSIS-DSP",
    platform: ["library"],
    tags: ["embedded", "arm", "c"],
    url: "https://github.com/ARM-software/CMSIS-DSP",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
