import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const EMBEDDED: Resource[] = [
  {
    access: "freemium",
    category: "embedded",
    description:
      "Browser simulator for Arduino, ESP32, and STM32. No hardware needed.",
    featured: true,
    id: "wokwi",
    isOpenSource: false,
    name: "Wokwi",
    platform: ["web"],
    requiresAccount: true,
    tags: ["simulator", "arduino", "esp32", "stm32"],
    url: "https://wokwi.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Beginner circuit and Arduino simulation.",
    id: "tinkercad-circuits",
    isOpenSource: false,
    name: "Tinkercad Circuits",
    platform: ["web"],
    requiresAccount: true,
    tags: ["simulator", "arduino"],
    url: "https://www.tinkercad.com/circuits",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Official ST toolchain with peripheral configuration.",
    featured: true,
    id: "stm32cubeide",
    isOpenSource: false,
    name: "STM32CubeIDE",
    platform: ["desktop"],
    requiresAccount: true,
    tags: ["ide", "stm32", "arm"],
    url: "https://www.st.com/en/development-tools/stm32cubeide.html",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "embedded",
    description:
      "ARM Cortex-M environment; free community edition for education.",
    id: "keil-mdk",
    isOpenSource: false,
    name: "Keil MDK",
    platform: ["desktop"],
    tags: ["ide", "arm"],
    url: "https://www.keil.arm.com",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Cross-platform build system inside VS Code.",
    featured: true,
    id: "platformio",
    isOpenSource: true,
    name: "PlatformIO",
    platform: ["cli", "desktop"],
    tags: ["build", "ide"],
    url: "https://platformio.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Official Arduino development environment.",
    id: "arduino-ide",
    isOpenSource: true,
    name: "Arduino IDE",
    platform: ["desktop"],
    tags: ["ide", "arduino"],
    url: "https://www.arduino.cc/en/software",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Espressif framework for ESP32 work.",
    id: "esp-idf",
    isOpenSource: true,
    name: "ESP-IDF",
    platform: ["library"],
    tags: ["esp32", "framework"],
    url: "https://idf.espressif.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "The RTOS the course names, with docs and demos.",
    featured: true,
    id: "freertos",
    isOpenSource: true,
    name: "FreeRTOS",
    platform: ["library"],
    tags: ["rtos"],
    url: "https://www.freertos.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Scalable RTOS with a modern build system.",
    featured: true,
    id: "zephyr",
    isOpenSource: true,
    name: "Zephyr",
    platform: ["library"],
    tags: ["rtos"],
    url: "https://www.zephyrproject.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "RTOS for constrained IoT nodes.",
    id: "riot-os",
    isOpenSource: true,
    name: "RIOT",
    platform: ["library"],
    tags: ["rtos", "iot"],
    url: "https://www.riot-os.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Python on microcontrollers for fast prototyping.",
    id: "micropython",
    isOpenSource: true,
    name: "MicroPython",
    platform: ["library"],
    tags: ["python", "mcu"],
    url: "https://micropython.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Instruction-accurate emulation of embedded systems.",
    featured: true,
    id: "renode",
    isOpenSource: true,
    name: "Renode",
    platform: ["desktop"],
    tags: ["emulator", "arm"],
    url: "https://renode.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "General emulator with Cortex-M board support.",
    id: "qemu",
    isOpenSource: true,
    name: "QEMU",
    platform: ["desktop", "cli"],
    tags: ["emulator"],
    url: "https://www.qemu.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Logic analysis with I2C, SPI, UART, and CAN decoders.",
    id: "saleae-logic",
    isOpenSource: false,
    name: "Saleae Logic 2",
    note: "The software is free; the analyser is hardware.",
    platform: ["desktop"],
    tags: ["logic analyser", "debug"],
    url: "https://www.saleae.com/downloads",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Open signal capture and protocol decoding.",
    id: "sigrok-pulseview",
    isOpenSource: true,
    name: "sigrok and PulseView",
    platform: ["desktop"],
    tags: ["logic analyser", "debug"],
    url: "https://sigrok.org/wiki/PulseView",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "On-chip debug and flash for ARM targets.",
    id: "openocd",
    isOpenSource: true,
    name: "OpenOCD",
    platform: ["cli"],
    tags: ["debug", "jtag"],
    url: "https://openocd.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Scriptable debug and flash tool for Cortex-M.",
    id: "pyocd",
    isOpenSource: true,
    name: "pyOCD",
    platform: ["cli"],
    tags: ["debug", "python"],
    url: "https://pyocd.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Schematic and PCB design.",
    featured: true,
    id: "kicad",
    isOpenSource: true,
    name: "KiCad",
    platform: ["desktop"],
    tags: ["pcb", "schematic"],
    url: "https://www.kicad.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Interactive circuit simulation in the browser.",
    id: "falstad-circuit",
    isOpenSource: true,
    name: "Falstad Circuit Simulator",
    platform: ["web"],
    tags: ["circuit", "simulator"],
    url: "https://www.falstad.com/circuit",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "embedded",
    description: "Browser circuit simulation.",
    id: "circuitlab",
    isOpenSource: false,
    name: "CircuitLab",
    platform: ["web"],
    requiresAccount: true,
    tags: ["circuit", "simulator"],
    url: "https://www.circuitlab.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Browser multi-board emulator, new in 2026.",
    id: "velxio",
    isOpenSource: true,
    name: "Velxio",
    platform: ["web"],
    status: "experimental",
    tags: ["emulator", "arduino", "esp32"],
    url: "https://velxio.dev",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "POSIX-style RTOS for deeply embedded systems.",
    id: "nuttx",
    isOpenSource: true,
    name: "Apache NuttX",
    platform: ["library"],
    tags: ["rtos"],
    url: "https://nuttx.apache.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Firmware library for Cortex-M without vendor generators.",
    id: "libopencm3",
    isOpenSource: true,
    name: "libopencm3",
    platform: ["library"],
    tags: ["arm", "firmware"],
    url: "https://libopencm3.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "embedded",
    description: "Scripted Arduino builds for CI.",
    id: "arduino-cli",
    isOpenSource: true,
    name: "arduino-cli",
    platform: ["cli"],
    tags: ["arduino", "cli"],
    url: "https://arduino.github.io/arduino-cli",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
