import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const FILE_UTILITIES: Resource[] = [
  {
    access: "freemium",
    category: "file-utilities",
    description: "Merge, split, compress, convert, and sign PDFs.",
    featured: true,
    id: "ilovepdf",
    isOpenSource: false,
    name: "iLovePDF",
    platform: ["web"],
    tags: ["pdf", "converter"],
    url: "https://www.ilovepdf.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "file-utilities",
    description: "Compress, resize, crop, and convert images.",
    featured: true,
    id: "iloveimg",
    isOpenSource: false,
    name: "iLoveIMG",
    platform: ["web"],
    tags: ["image", "converter"],
    url: "https://www.iloveimg.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "file-utilities",
    description: "PDF editing, compression, and OCR.",
    id: "smallpdf",
    isOpenSource: false,
    name: "Smallpdf",
    platform: ["web"],
    tags: ["pdf", "ocr"],
    url: "https://smallpdf.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "file-utilities",
    description: "Browser and desktop PDF tools with no upload quota.",
    featured: true,
    id: "pdf24",
    isOpenSource: false,
    name: "PDF24 Tools",
    platform: ["web", "desktop"],
    tags: ["pdf"],
    url: "https://tools.pdf24.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "file-utilities",
    description:
      "Self-hosted PDF toolkit when files must stay on your machine.",
    id: "stirling-pdf",
    isOpenSource: true,
    name: "Stirling PDF",
    platform: ["web", "desktop"],
    tags: ["pdf", "self-hosted"],
    url: "https://www.stirlingpdf.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "file-utilities",
    description: "Converts documents, audio, and video between formats.",
    id: "cloudconvert",
    isOpenSource: false,
    name: "CloudConvert",
    platform: ["web"],
    tags: ["converter"],
    url: "https://cloudconvert.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "file-utilities",
    description: "Compress lecture recordings for storage.",
    id: "handbrake",
    isOpenSource: true,
    name: "HandBrake",
    platform: ["desktop"],
    tags: ["video", "converter"],
    url: "https://handbrake.fr",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Photopea",
    category: "file-utilities",
    description: "Photoshop-style editing in the browser.",
    id: "photopea",
    isOpenSource: false,
    name: "Photopea",
    platform: ["web"],
    tags: ["image", "editor"],
    url: "https://www.photopea.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Gimp",
    category: "file-utilities",
    description: "Raster image editor for figure cleanup.",
    id: "gimp",
    isOpenSource: true,
    name: "GIMP",
    platform: ["desktop"],
    tags: ["image", "editor"],
    url: "https://www.gimp.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "file-utilities",
    description: "Batch image conversion from the command line.",
    id: "imagemagick",
    isOpenSource: true,
    name: "ImageMagick",
    platform: ["cli"],
    tags: ["image", "converter"],
    url: "https://imagemagick.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "file-utilities",
    description: "Compare text, code, images, and PDFs.",
    id: "diffchecker",
    isOpenSource: false,
    name: "Diffchecker",
    platform: ["web"],
    tags: ["diff"],
    url: "https://www.diffchecker.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Acrobat Reader",
    category: "file-utilities",
    description: "Basic PDF operations from Adobe.",
    id: "adobe-acrobat-online",
    isOpenSource: false,
    name: "Adobe Acrobat online",
    platform: ["web"],
    requiresAccount: true,
    tags: ["pdf"],
    url: "https://www.adobe.com/acrobat/online.html",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "file-utilities",
    description:
      "Folder sync between laptop and desktop without a cloud account.",
    id: "syncthing",
    isOpenSource: true,
    name: "Syncthing",
    platform: ["desktop"],
    tags: ["sync"],
    url: "https://syncthing.net",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
