import { AI_PRIVACY_NOTE } from "@/config/resources/copy";
import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const INTEGRITY_ARCHIVING: Resource[] = [
  {
    access: "university",
    category: "integrity-archiving",
    description: "The official similarity check, if the department uses it.",
    id: "turnitin",
    isOpenSource: false,
    name: "Turnitin",
    platform: ["web"],
    tags: ["similarity"],
    thesisStages: ["integrity"],
    url: "https://www.turnitin.com",
    verification: "liu",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "integrity-archiving",
    description: "Source code similarity for the software chapter.",
    featured: true,
    id: "jplag",
    isOpenSource: true,
    name: "JPlag",
    platform: ["cli"],
    tags: ["similarity", "code"],
    thesisStages: ["integrity"],
    url: "https://github.com/jplag/JPlag",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "integrity-archiving",
    description: "Text similarity and AI-content checks.",
    id: "copyleaks",
    isOpenSource: false,
    name: "Copyleaks",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["similarity"],
    thesisStages: ["integrity"],
    url: "https://copyleaks.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "integrity-archiving",
    description: "Deep-search similarity pass for drafts.",
    id: "quetext",
    isOpenSource: false,
    name: "Quetext",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    tags: ["similarity"],
    thesisStages: ["integrity"],
    url: "https://www.quetext.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "integrity-archiving",
    description: "Second opinion on similarity before the advisor sees it.",
    id: "duplichecker",
    isOpenSource: false,
    name: "DupliChecker",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    tags: ["similarity"],
    thesisStages: ["integrity"],
    url: "https://www.duplichecker.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    category: "integrity-archiving",
    description: "Student-oriented checker plus writing guides.",
    id: "scribbr-checker",
    isOpenSource: false,
    name: "Scribbr plagiarism checker",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    tags: ["similarity"],
    thesisStages: ["integrity"],
    url: "https://www.scribbr.com/plagiarism-checker",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    category: "integrity-archiving",
    description: "Publisher-grade similarity check.",
    id: "ithenticate",
    isOpenSource: false,
    name: "iThenticate",
    platform: ["web"],
    tags: ["similarity"],
    url: "https://www.ithenticate.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "integrity-archiving",
    description: "Mint a DOI for code and data at submission.",
    featured: true,
    id: "zenodo",
    isOpenSource: false,
    name: "Zenodo",
    platform: ["web"],
    requiresAccount: true,
    tags: ["doi", "archive"],
    thesisStages: ["integrity"],
    url: "https://zenodo.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Open Science Framework"],
    category: "integrity-archiving",
    description: "Project workspace, preregistration, and file sharing.",
    featured: true,
    id: "osf",
    isOpenSource: true,
    name: "OSF",
    platform: ["web"],
    requiresAccount: true,
    tags: ["archive", "preregistration"],
    thesisStages: ["integrity", "defend"],
    url: "https://osf.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "integrity-archiving",
    description: "Persistent researcher identifier.",
    id: "orcid",
    isOpenSource: false,
    name: "ORCID",
    platform: ["web"],
    requiresAccount: true,
    tags: ["identifier"],
    thesisStages: ["integrity"],
    url: "https://orcid.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "integrity-archiving",
    description: "Scores a repository against FAIR guidance.",
    id: "howfairis",
    isOpenSource: true,
    name: "howfairis",
    platform: ["cli"],
    tags: ["fair", "repository"],
    thesisStages: ["integrity"],
    url: "https://github.com/fair-software/howfairis",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
