import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const LEARNING: Resource[] = [
  {
    access: "free",
    category: "learning",
    description:
      "Spaced repetition flashcards. Desktop and Android are free; iOS is paid.",
    id: "anki",
    isOpenSource: true,
    name: "Anki",
    platform: ["desktop"],
    tags: ["flashcards"],
    url: "https://apps.ankiweb.net",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "learning",
    description: "Flashcards and quiz modes.",
    id: "quizlet",
    isOpenSource: false,
    name: "Quizlet",
    platform: ["web"],
    requiresAccount: true,
    tags: ["flashcards"],
    url: "https://quizlet.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "learning",
    description: "Free courses on math and computing.",
    id: "khan-academy",
    isOpenSource: false,
    name: "Khan Academy",
    platform: ["web"],
    tags: ["courses"],
    url: "https://www.khanacademy.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "learning",
    description: "Lecture notes, exams, and videos from MIT courses.",
    id: "mit-ocw",
    isOpenSource: false,
    name: "MIT OpenCourseWare",
    platform: ["web"],
    tags: ["courses"],
    url: "https://ocw.mit.edu",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Coursera",
    category: "learning",
    description: "Audit university courses free, pay for certificates.",
    id: "coursera",
    isOpenSource: false,
    name: "Coursera",
    platform: ["web"],
    requiresAccount: true,
    tags: ["courses"],
    url: "https://www.coursera.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "learning",
    description: "University courses, audit track free.",
    id: "edx",
    isOpenSource: false,
    name: "edX",
    platform: ["web"],
    requiresAccount: true,
    tags: ["courses"],
    url: "https://www.edx.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "learning",
    description: "Free coding curriculum.",
    id: "freecodecamp",
    isOpenSource: true,
    name: "freeCodeCamp",
    platform: ["web"],
    tags: ["courses", "coding"],
    url: "https://www.freecodecamp.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Cloudflare",
    category: "learning",
    description: "Plain explanations of networking concepts.",
    id: "cloudflare-learning-center",
    isOpenSource: false,
    name: "Cloudflare Learning Center",
    platform: ["web"],
    tags: ["networking", "reference"],
    url: "https://www.cloudflare.com/learning",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "learning",
    description: "Academic writing and citation guidance.",
    id: "purdue-owl",
    isOpenSource: false,
    name: "Purdue OWL",
    platform: ["web"],
    tags: ["writing", "citation"],
    url: "https://owl.purdue.edu",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
