import { AI_PRIVACY_NOTE } from "@/config/resources/copy";
import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const LITERATURE: Resource[] = [
  {
    access: "free",
    brandIcon: "Google",
    category: "literature",
    description: "Broadest coverage and the standard citation tracker.",
    featured: true,
    id: "google-scholar",
    isOpenSource: false,
    name: "Google Scholar",
    platform: ["web"],
    tags: ["search", "papers", "citations"],
    thesisStages: ["search"],
    url: "https://scholar.google.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Metadata-rich search with an open API and TLDRs.",
    featured: true,
    id: "semantic-scholar",
    isOpenSource: false,
    name: "Semantic Scholar",
    platform: ["web"],
    tags: ["search", "papers", "api"],
    thesisStages: ["search"],
    url: "https://www.semanticscholar.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Preprints across ML, signals, networking, and security.",
    featured: true,
    id: "arxiv",
    isOpenSource: false,
    name: "arXiv",
    platform: ["web"],
    tags: ["preprint", "papers"],
    thesisStages: ["search", "retrieve"],
    url: "https://arxiv.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Open scholarly graph with a free API.",
    featured: true,
    id: "openalex",
    isOpenSource: true,
    name: "OpenAlex",
    platform: ["web"],
    tags: ["graph", "api", "papers"],
    thesisStages: ["frame", "search"],
    url: "https://openalex.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Clean computer science bibliography for venue checks.",
    id: "dblp",
    isOpenSource: false,
    name: "DBLP",
    platform: ["web"],
    tags: ["bibliography", "venues"],
    thesisStages: ["frame"],
    url: "https://dblp.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Open access aggregation with full-text search.",
    id: "core",
    isOpenSource: false,
    name: "CORE",
    platform: ["web"],
    tags: ["open access", "papers"],
    thesisStages: ["retrieve"],
    url: "https://core.ac.uk",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Bielefeld Academic Search Engine"],
    category: "literature",
    description: "Bielefeld index over institutional repositories.",
    id: "base",
    isOpenSource: false,
    name: "BASE",
    platform: ["web"],
    tags: ["open access", "search"],
    thesisStages: ["search"],
    url: "https://www.base-search.net",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Directory of Open Access Journals"],
    category: "literature",
    description: "Directory of open access journals; vet a venue here.",
    id: "doaj",
    isOpenSource: false,
    name: "DOAJ",
    platform: ["web"],
    tags: ["journals", "open access"],
    thesisStages: ["frame"],
    url: "https://doaj.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Finds a legal open copy of a paywalled DOI.",
    featured: true,
    id: "unpaywall",
    isOpenSource: true,
    name: "Unpaywall",
    platform: ["web"],
    tags: ["open access", "doi"],
    thesisStages: ["retrieve"],
    url: "https://unpaywall.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Open copy finder with a request flow.",
    id: "open-access-button",
    isOpenSource: true,
    name: "Open Access Button",
    platform: ["web"],
    tags: ["open access"],
    thesisStages: ["retrieve"],
    url: "https://openaccessbutton.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Research Rabbit"],
    category: "literature",
    description: "Citation network mapping from seed papers with Zotero sync.",
    featured: true,
    id: "research-rabbit",
    isOpenSource: false,
    name: "ResearchRabbit",
    platform: ["web"],
    requiresAccount: true,
    tags: ["citation graph", "mapping"],
    thesisStages: ["map"],
    url: "https://www.researchrabbit.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description:
      "Co-citation graph from one seed paper. Five graphs a month free.",
    featured: true,
    id: "connected-papers",
    isOpenSource: false,
    name: "Connected Papers",
    platform: ["web"],
    tags: ["citation graph", "mapping"],
    thesisStages: ["map"],
    url: "https://www.connectedpapers.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Timeline view of a citation network.",
    id: "litmaps",
    isOpenSource: false,
    name: "Litmaps",
    platform: ["web"],
    requiresAccount: true,
    tags: ["citation graph", "mapping"],
    thesisStages: ["map"],
    url: "https://www.litmaps.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Finds bridge paths between two papers.",
    id: "inciteful",
    isOpenSource: false,
    name: "Inciteful",
    platform: ["web"],
    tags: ["citation graph", "mapping"],
    thesisStages: ["map"],
    url: "https://inciteful.xyz",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Concept map from a keyword when there is no seed paper.",
    id: "open-knowledge-maps",
    isOpenSource: false,
    name: "Open Knowledge Maps",
    platform: ["web"],
    tags: ["mapping", "concepts"],
    thesisStages: ["frame"],
    url: "https://openknowledgemaps.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Extracts methods and findings into a comparison table.",
    featured: true,
    id: "elicit",
    isOpenSource: false,
    name: "Elicit",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["extraction", "ai", "review"],
    thesisStages: ["screen"],
    url: "https://elicit.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Agreement signals across papers for a claim.",
    id: "consensus",
    isOpenSource: false,
    name: "Consensus",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["ai", "evidence"],
    thesisStages: ["screen"],
    url: "https://consensus.app",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Whether later work supported or disputed a claim.",
    id: "scite",
    isOpenSource: false,
    name: "scite",
    platform: ["web"],
    requiresAccount: true,
    tags: ["citations", "context"],
    thesisStages: ["map"],
    url: "https://scite.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Slow multi-hop search that surfaces long-tail papers.",
    id: "undermind",
    isOpenSource: false,
    name: "Undermind",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["search", "ai"],
    thesisStages: ["search"],
    url: "https://www.undermind.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    aliases: ["Typeset"],
    category: "literature",
    description: "Paper explainers and a review workspace.",
    id: "scispace",
    isOpenSource: false,
    name: "SciSpace",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["reading", "ai"],
    thesisStages: ["screen"],
    url: "https://scispace.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Highlight a passage and get an explanation.",
    id: "explainpaper",
    isOpenSource: false,
    name: "Explainpaper",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["reading", "ai"],
    thesisStages: ["screen"],
    url: "https://www.explainpaper.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Ask questions about one uploaded PDF.",
    id: "chatpdf",
    isOpenSource: false,
    name: "ChatPDF",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["reading", "ai", "pdf"],
    thesisStages: ["screen"],
    url: "https://www.chatpdf.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Google",
    category: "literature",
    description: "Venue ranking by h5-index.",
    id: "google-scholar-metrics",
    isOpenSource: false,
    name: "Google Scholar Metrics",
    platform: ["web"],
    tags: ["venues", "ranking"],
    thesisStages: ["frame"],
    url: "https://scholar.google.com/citations?view_op=top_venues",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["SJR"],
    category: "literature",
    description: "Journal quartiles for target venues.",
    id: "scimago",
    isOpenSource: false,
    name: "Scimago Journal Rank",
    platform: ["web"],
    tags: ["journals", "ranking"],
    thesisStages: ["frame"],
    url: "https://www.scimagojr.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "The core archive for comms, DSP, and embedded literature.",
    featured: true,
    id: "ieee-xplore",
    isOpenSource: false,
    name: "IEEE Xplore",
    note: "Abstracts and search are free; full text needs a subscription, often through a university library.",
    platform: ["web"],
    tags: ["database", "papers"],
    thesisStages: ["search"],
    url: "https://ieeexplore.ieee.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Computing, security, and systems literature.",
    id: "acm-dl",
    isOpenSource: false,
    name: "ACM Digital Library",
    note: "Abstracts and search are free; full text needs a subscription, often through a university library.",
    platform: ["web"],
    tags: ["database", "papers"],
    thesisStages: ["search"],
    url: "https://dl.acm.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    category: "literature",
    description: "Citation database for bibliometrics.",
    id: "scopus",
    isOpenSource: false,
    name: "Scopus",
    note: "Subscription database, usually reached through a university library.",
    platform: ["web"],
    tags: ["database", "citations"],
    thesisStages: ["search"],
    url: "https://www.scopus.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    category: "literature",
    description: "Citation tracking across publishers.",
    id: "web-of-science",
    isOpenSource: false,
    name: "Web of Science",
    note: "Subscription database, usually reached through a university library.",
    platform: ["web"],
    tags: ["database", "citations"],
    thesisStages: ["search"],
    url: "https://www.webofscience.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Springer journals and book chapters.",
    id: "springerlink",
    isOpenSource: false,
    name: "SpringerLink",
    note: "Abstracts and open access papers are free; the rest needs a subscription.",
    platform: ["web"],
    tags: ["database", "papers"],
    thesisStages: ["search"],
    url: "https://link.springer.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Elsevier journals, strong in signals and control.",
    id: "sciencedirect",
    isOpenSource: false,
    name: "ScienceDirect",
    note: "Abstracts and open access papers are free; the rest needs a subscription.",
    platform: ["web"],
    tags: ["database", "papers"],
    thesisStages: ["search"],
    url: "https://www.sciencedirect.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "literature",
    description: "Engineering datasets, RF captures, and IoT traffic.",
    id: "ieee-dataport",
    isOpenSource: false,
    name: "IEEE DataPort",
    platform: ["dataset"],
    requiresAccount: true,
    tags: ["dataset"],
    url: "https://ieee-dataport.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "literature",
    description: "Scholarly search over archived web content.",
    id: "internet-archive-scholar",
    isOpenSource: false,
    name: "Internet Archive Scholar",
    platform: ["web"],
    tags: ["search", "archive"],
    thesisStages: ["search"],
    url: "https://scholar.archive.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
