import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const MATH: Resource[] = [
  {
    access: "freemium",
    category: "math",
    description: "Step-by-step checks for transforms, series, and statistics.",
    featured: true,
    id: "wolfram-alpha",
    isOpenSource: false,
    name: "Wolfram Alpha",
    platform: ["web"],
    tags: ["symbolic", "solver"],
    url: "https://www.wolframalpha.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Fast function and signal plotting.",
    id: "desmos",
    isOpenSource: false,
    name: "Desmos",
    platform: ["web"],
    tags: ["plot", "graphing"],
    url: "https://www.desmos.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Geometry, calculus, and linear algebra visualisation.",
    id: "geogebra",
    isOpenSource: false,
    name: "GeoGebra",
    platform: ["web", "desktop"],
    tags: ["plot", "geometry"],
    url: "https://www.geogebra.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "math",
    description: "Step-by-step solver for homework checks.",
    id: "symbolab",
    isOpenSource: false,
    name: "Symbolab",
    platform: ["web"],
    tags: ["solver"],
    url: "https://www.symbolab.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Octave"],
    category: "math",
    description: "MATLAB-compatible environment with no license friction.",
    featured: true,
    id: "gnu-octave",
    isOpenSource: true,
    name: "GNU Octave",
    platform: ["desktop", "cli"],
    tags: ["matlab", "numerical"],
    thesisStages: ["experiment"],
    url: "https://octave.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    aliases: ["MathWorks"],
    brandIcon: "matlab",
    category: "math",
    description: "Standard for DSP and communications teaching.",
    id: "matlab",
    isOpenSource: false,
    name: "MATLAB",
    note: "Student license from MathWorks; free where a campus license exists.",
    platform: ["desktop"],
    tags: ["numerical", "simulation"],
    thesisStages: ["experiment"],
    url: "https://www.mathworks.com/academia/students.html",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "student",
    brandIcon: "matlab",
    category: "math",
    description:
      "Block-based system and signal modelling. Same license question as MATLAB.",
    id: "simulink",
    isOpenSource: false,
    name: "Simulink",
    note: "Sold with the MATLAB student license.",
    platform: ["desktop"],
    tags: ["simulation"],
    url: "https://www.mathworks.com/products/simulink.html",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Sage"],
    category: "math",
    description:
      "Symbolic engine covering algebra, calculus, and number theory.",
    featured: true,
    id: "sagemath",
    isOpenSource: true,
    name: "SageMath",
    platform: ["desktop", "web"],
    tags: ["symbolic", "algebra"],
    url: "https://www.sagemath.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description:
      "Symbolic algebra in Python for series, integrals, and Z transforms.",
    id: "sympy",
    isOpenSource: true,
    name: "SymPy",
    platform: ["library"],
    tags: ["symbolic", "python"],
    url: "https://www.sympy.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Julia",
    category: "math",
    description: "Fast numerics for optimisation and simulation code.",
    id: "julia",
    isOpenSource: true,
    name: "Julia",
    platform: ["desktop", "cli"],
    tags: ["numerical", "language"],
    url: "https://julialang.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Graph algorithms for the graph theory block.",
    id: "networkx",
    isOpenSource: true,
    name: "NetworkX",
    platform: ["library"],
    tags: ["graph", "python"],
    url: "https://networkx.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Discrete-event simulation for queues.",
    id: "simpy",
    isOpenSource: true,
    name: "SimPy",
    platform: ["library"],
    tags: ["simulation", "queue", "python"],
    url: "https://simpy.readthedocs.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Linear programming modeller in Python.",
    id: "pulp",
    isOpenSource: true,
    name: "PuLP",
    platform: ["library"],
    tags: ["optimisation", "python"],
    url: "https://coin-or.github.io/pulp",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Convex optimisation modelling.",
    id: "cvxpy",
    isOpenSource: true,
    name: "CVXPY",
    platform: ["library"],
    tags: ["optimisation", "python"],
    url: "https://www.cvxpy.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Routing, scheduling, and assignment solvers.",
    id: "or-tools",
    isOpenSource: true,
    name: "OR-Tools",
    platform: ["library"],
    tags: ["optimisation"],
    url: "https://developers.google.com/optimization",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description:
      "Algebraic modelling for linear, integer, and nonlinear programs.",
    id: "pyomo",
    isOpenSource: true,
    name: "Pyomo",
    platform: ["library"],
    tags: ["optimisation", "python"],
    url: "https://www.pyomo.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Fast open linear and mixed-integer solver.",
    id: "highs",
    isOpenSource: true,
    name: "HiGHS",
    platform: ["library"],
    tags: ["optimisation", "solver"],
    url: "https://highs.dev",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Hidden Markov models in Python.",
    id: "hmmlearn",
    isOpenSource: true,
    name: "hmmlearn",
    platform: ["library"],
    tags: ["markov", "python"],
    url: "https://hmmlearn.readthedocs.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "math",
    description: "Desktop plotting and curve fitting for lab reports.",
    id: "labplot",
    isOpenSource: true,
    name: "LabPlot",
    platform: ["desktop"],
    tags: ["plot"],
    url: "https://labplot.kde.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
