import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const ML: Resource[] = [
  {
    access: "freemium",
    aliases: ["Colab"],
    brandIcon: "Google Colaboratory",
    category: "ml",
    description:
      "Hosted notebooks with a free GPU, the path of least resistance for the ML lab.",
    featured: true,
    id: "google-colab",
    isOpenSource: false,
    name: "Google Colab",
    platform: ["web"],
    requiresAccount: true,
    tags: ["notebook", "gpu", "compute"],
    thesisStages: ["experiment"],
    url: "https://colab.research.google.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Datasets, notebooks, competitions, and weekly GPU quota.",
    featured: true,
    id: "kaggle",
    isOpenSource: false,
    name: "Kaggle",
    platform: ["web"],
    requiresAccount: true,
    tags: ["dataset", "notebook", "gpu"],
    thesisStages: ["experiment"],
    url: "https://www.kaggle.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Hugging Face",
    category: "ml",
    description: "Pretrained models, datasets, and Spaces for demos.",
    featured: true,
    id: "hugging-face",
    isOpenSource: false,
    name: "Hugging Face",
    platform: ["web"],
    requiresAccount: true,
    tags: ["models", "dataset"],
    url: "https://huggingface.co",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    aliases: ["W&B", "wandb"],
    category: "ml",
    description:
      "Experiment tracking that turns scattered runs into one table.",
    id: "weights-and-biases",
    isOpenSource: false,
    name: "Weights and Biases",
    platform: ["web", "library"],
    requiresAccount: true,
    tags: ["tracking"],
    thesisStages: ["experiment"],
    url: "https://wandb.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Self-hosted run tracking and model registry.",
    featured: true,
    id: "mlflow",
    isOpenSource: true,
    name: "MLflow",
    platform: ["library"],
    tags: ["tracking", "self-hosted"],
    thesisStages: ["experiment"],
    url: "https://mlflow.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Hyperparameter search with pruning.",
    id: "optuna",
    isOpenSource: true,
    name: "Optuna",
    platform: ["library"],
    tags: ["tuning", "python"],
    thesisStages: ["experiment"],
    url: "https://optuna.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Default deep learning framework for custom models.",
    featured: true,
    id: "pytorch",
    isOpenSource: true,
    name: "PyTorch",
    platform: ["library"],
    tags: ["deep learning", "python"],
    thesisStages: ["experiment"],
    url: "https://pytorch.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Keras"],
    brandIcon: "TensorFlow",
    category: "ml",
    description: "Alternative stack required by some published baselines.",
    id: "tensorflow",
    isOpenSource: true,
    name: "TensorFlow and Keras",
    platform: ["library"],
    tags: ["deep learning", "python"],
    url: "https://www.tensorflow.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Lightning"],
    category: "ml",
    description: "Training loop scaffolding for comparable experiments.",
    id: "pytorch-lightning",
    isOpenSource: true,
    name: "PyTorch Lightning",
    platform: ["library"],
    tags: ["deep learning", "python"],
    url: "https://lightning.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["sklearn"],
    category: "ml",
    description:
      "The classical algorithms the syllabus teaches, ready for baselines.",
    featured: true,
    id: "scikit-learn",
    isOpenSource: true,
    name: "scikit-learn",
    platform: ["library"],
    tags: ["python", "classification", "clustering"],
    thesisStages: ["experiment"],
    url: "https://scikit-learn.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Feature attribution for tree and neural models.",
    id: "shap",
    isOpenSource: true,
    name: "SHAP",
    platform: ["library"],
    tags: ["explainability", "python"],
    url: "https://shap.readthedocs.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Attribution methods for PyTorch models.",
    id: "captum",
    isOpenSource: true,
    name: "Captum",
    platform: ["library"],
    tags: ["explainability", "pytorch"],
    url: "https://captum.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Visualise ONNX, PyTorch, and TensorFlow model graphs.",
    id: "netron",
    isOpenSource: true,
    name: "Netron",
    platform: ["web", "desktop"],
    tags: ["visualiser", "onnx"],
    url: "https://netron.app",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "TensorFlow",
    category: "ml",
    description: "Training curves and embedding projection.",
    id: "tensorboard",
    isOpenSource: true,
    name: "TensorBoard",
    platform: ["library"],
    tags: ["tracking", "visualiser"],
    url: "https://www.tensorflow.org/tensorboard",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Resampling for skewed classes.",
    id: "imbalanced-learn",
    isOpenSource: true,
    name: "imbalanced-learn",
    platform: ["library"],
    tags: ["python", "resampling"],
    url: "https://imbalanced-learn.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Visual diagnostics for model selection.",
    id: "yellowbrick",
    isOpenSource: true,
    name: "Yellowbrick",
    platform: ["library"],
    tags: ["python", "diagnostics"],
    url: "https://www.scikit-yb.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["UCI"],
    category: "ml",
    description: "Benchmark datasets reviewers recognise.",
    id: "uci-ml-repository",
    isOpenSource: false,
    name: "UCI Machine Learning Repository",
    platform: ["dataset"],
    tags: ["dataset"],
    url: "https://archive.ics.uci.edu",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Datasets, tasks, and shared experiments.",
    id: "openml",
    isOpenSource: false,
    name: "OpenML",
    platform: ["dataset"],
    tags: ["dataset"],
    url: "https://www.openml.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Google",
    category: "ml",
    description: "Search engine for open datasets.",
    id: "google-dataset-search",
    isOpenSource: false,
    name: "Google Dataset Search",
    platform: ["web"],
    tags: ["dataset", "search"],
    url: "https://datasetsearch.research.google.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description:
      "Papers paired with implementations. Confirm the site still resolves.",
    id: "papers-with-code",
    isOpenSource: false,
    name: "Papers with Code",
    platform: ["web"],
    tags: ["papers", "code", "benchmark"],
    thesisStages: ["frame"],
    url: "https://paperswithcode.com",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Data and model versioning beside Git.",
    featured: true,
    id: "dvc",
    isOpenSource: true,
    name: "DVC",
    platform: ["cli"],
    tags: ["versioning", "reproducibility"],
    thesisStages: ["experiment"],
    url: "https://dvc.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Gradio",
    category: "ml",
    description: "Quick demo UI for a trained model at the defense.",
    id: "gradio",
    isOpenSource: true,
    name: "Gradio",
    platform: ["library"],
    tags: ["demo", "python"],
    thesisStages: ["defend"],
    url: "https://www.gradio.app",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Google",
    category: "ml",
    description: "Train a small model in the browser with no code.",
    id: "teachable-machine",
    isOpenSource: false,
    name: "Teachable Machine",
    platform: ["web"],
    tags: ["demo", "no-code"],
    url: "https://teachablemachine.withgoogle.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description:
      "Distributed training and tuning when one machine is not enough.",
    id: "ray",
    isOpenSource: true,
    name: "Ray",
    platform: ["library"],
    tags: ["distributed", "python"],
    url: "https://www.ray.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Pipelines as a rerunnable directed graph.",
    id: "snakemake",
    isOpenSource: true,
    name: "Snakemake",
    platform: ["cli"],
    tags: ["pipeline", "reproducibility"],
    thesisStages: ["experiment"],
    url: "https://snakemake.github.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Experiment configuration as files, not code edits.",
    id: "hydra",
    isOpenSource: true,
    name: "Hydra",
    platform: ["library"],
    tags: ["configuration", "python"],
    thesisStages: ["experiment"],
    url: "https://hydra.cc",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "ml",
    description: "Self-hosted run comparison across many experiments.",
    id: "aim",
    isOpenSource: true,
    name: "Aim",
    platform: ["library"],
    tags: ["tracking", "self-hosted"],
    url: "https://aimstack.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
