import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const MULTIMEDIA: Resource[] = [
  {
    access: "free",
    category: "multimedia",
    description: "Transcode, mux, demux, and stream from the command line.",
    featured: true,
    id: "ffmpeg",
    isOpenSource: true,
    name: "FFmpeg",
    platform: ["cli"],
    tags: ["video", "audio", "converter"],
    url: "https://ffmpeg.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["MP4Box"],
    category: "multimedia",
    description: "MP4 and MPEG-DASH packaging for delivery research.",
    id: "gpac",
    isOpenSource: true,
    name: "GPAC and MP4Box",
    platform: ["cli"],
    tags: ["streaming", "dash"],
    url: "https://gpac.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "multimedia",
    description: "Playback with stream inspection and codec reporting.",
    id: "vlc",
    isOpenSource: true,
    name: "VLC",
    platform: ["desktop"],
    tags: ["player"],
    url: "https://www.videolan.org/vlc",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "multimedia",
    description: "Codec, bitrate, and container details for any file.",
    id: "mediainfo",
    isOpenSource: true,
    name: "MediaInfo",
    platform: ["desktop"],
    tags: ["metadata"],
    url: "https://mediaarea.net/en/MediaInfo",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Netflix",
    category: "multimedia",
    description: "Perceptual video quality metric for compression comparisons.",
    id: "vmaf",
    isOpenSource: true,
    name: "Netflix VMAF",
    platform: ["library"],
    tags: ["quality", "metric"],
    url: "https://github.com/Netflix/vmaf",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "OBS",
    category: "multimedia",
    description: "Record lab demos and defense dry runs.",
    id: "obs-studio",
    isOpenSource: true,
    name: "OBS Studio",
    platform: ["desktop"],
    tags: ["recording"],
    thesisStages: ["defend"],
    url: "https://obsproject.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
