import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const NETWORKING: Resource[] = [
  {
    access: "free",
    category: "networking",
    description:
      "Packet capture and dissection across protocols and security work.",
    featured: true,
    id: "wireshark",
    isOpenSource: true,
    name: "Wireshark",
    platform: ["desktop"],
    tags: ["packets", "capture"],
    thesisStages: ["experiment"],
    url: "https://www.wireshark.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Command-line capture for headless runs.",
    id: "tcpdump",
    isOpenSource: true,
    name: "tcpdump",
    platform: ["cli"],
    tags: ["packets", "capture"],
    url: "https://www.tcpdump.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Emulates real router and switch images.",
    featured: true,
    id: "gns3",
    isOpenSource: true,
    name: "GNS3",
    platform: ["desktop"],
    tags: ["emulator", "topology"],
    url: "https://www.gns3.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "networking",
    description: "Network emulation lab platform.",
    id: "eve-ng",
    isOpenSource: false,
    name: "EVE-NG",
    platform: ["desktop"],
    tags: ["emulator", "lab"],
    url: "https://www.eve-ng.net",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["NS-3"],
    category: "networking",
    description:
      "Discrete-event simulator still standard in networking papers.",
    featured: true,
    id: "ns-3",
    isOpenSource: true,
    name: "ns-3",
    platform: ["library"],
    tags: ["simulation"],
    thesisStages: ["experiment"],
    url: "https://www.nsnam.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description:
      "SDN and OpenFlow testbed on one Linux kernel. Maintenance has slowed.",
    id: "mininet",
    isOpenSource: true,
    name: "Mininet",
    platform: ["desktop"],
    tags: ["sdn", "emulator"],
    url: "https://mininet.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Declarative container topologies with real routing images.",
    id: "containerlab",
    isOpenSource: true,
    name: "Containerlab",
    platform: ["cli"],
    tags: ["emulator", "containers"],
    url: "https://containerlab.dev",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Lightweight container-style topologies for IP labs.",
    id: "core-emulator",
    isOpenSource: true,
    name: "CORE",
    platform: ["desktop"],
    tags: ["emulator"],
    url: "https://github.com/coreemu/core",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["INET"],
    category: "networking",
    description: "Modular discrete-event modelling, free for academic use.",
    id: "omnetpp",
    isOpenSource: false,
    name: "OMNeT++ with INET",
    note: "Academic use is free; commercial use is licensed.",
    platform: ["desktop"],
    tags: ["simulation"],
    url: "https://omnetpp.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["FRR"],
    category: "networking",
    description: "BGP, OSPF, IS-IS, and MPLS on Linux.",
    id: "frrouting",
    isOpenSource: true,
    name: "FRRouting",
    platform: ["desktop"],
    tags: ["routing"],
    url: "https://frrouting.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Static analysis of network configurations.",
    id: "batfish",
    isOpenSource: true,
    name: "Batfish",
    platform: ["desktop"],
    tags: ["analysis", "config"],
    url: "https://batfish.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Bandwidth and jitter measurement.",
    id: "iperf3",
    isOpenSource: true,
    name: "iperf3",
    platform: ["cli"],
    tags: ["measurement"],
    url: "https://iperf.fr",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Inject delay, loss, and reordering on Linux.",
    id: "tc-netem",
    isOpenSource: true,
    name: "tc and netem",
    platform: ["cli"],
    tags: ["qos", "linux"],
    url: "https://wiki.linuxfoundation.org/networking/netem",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Craft, send, and dissect packets in Python.",
    id: "scapy",
    isOpenSource: true,
    name: "Scapy",
    platform: ["library"],
    tags: ["packets", "python"],
    url: "https://scapy.net",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["OVS"],
    category: "networking",
    description: "Virtual switch with OpenFlow for SDN labs.",
    id: "open-vswitch",
    isOpenSource: true,
    name: "Open vSwitch",
    platform: ["desktop"],
    tags: ["sdn", "switch"],
    url: "https://www.openvswitch.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "Programmable data plane and its reference switch.",
    id: "p4-bmv2",
    isOpenSource: true,
    name: "P4 and BMv2",
    platform: ["library"],
    tags: ["sdn", "p4"],
    url: "https://github.com/p4lang/behavioral-model",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "networking",
    description: "SDN controller for programmable control experiments.",
    id: "onos",
    isOpenSource: true,
    name: "ONOS",
    platform: ["desktop"],
    tags: ["sdn", "controller"],
    url: "https://opennetworking.org/onos",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["NetAcad"],
    brandIcon: "Cisco",
    category: "networking",
    description: "Networking courses and the Packet Tracer account.",
    id: "cisco-netacad",
    isOpenSource: false,
    name: "Cisco Networking Academy",
    platform: ["web"],
    requiresAccount: true,
    tags: ["courses"],
    url: "https://www.netacad.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
