import { AI_PRIVACY_NOTE } from "@/config/resources/copy";
import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const PRESENTATIONS: Resource[] = [
  {
    access: "freemium",
    brandIcon: "Canva",
    category: "presentations",
    description:
      "Slides, posters, and simple figures. Magic Design drafts a deck from a prompt.",
    id: "canva",
    isOpenSource: false,
    name: "Canva",
    platform: ["web"],
    requiresAccount: true,
    tags: ["slides", "deck", "design"],
    thesisStages: ["defend"],
    url: "https://www.canva.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Google Slides",
    category: "presentations",
    description: "Collaborative presentations.",
    id: "google-slides",
    isOpenSource: false,
    name: "Google Slides",
    platform: ["web"],
    requiresAccount: true,
    tags: ["slides", "deck", "presentation"],
    thesisStages: ["defend"],
    url: "https://slides.google.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "presentations",
    description: "Markdown to slide deck, kept in version control.",
    id: "marp",
    isOpenSource: true,
    name: "Marp",
    platform: ["cli"],
    tags: ["slides", "markdown"],
    thesisStages: ["defend"],
    url: "https://marp.app",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "presentations",
    description: "LaTeX slides that match the manuscript.",
    id: "beamer",
    isOpenSource: true,
    name: "Beamer",
    platform: ["library"],
    tags: ["slides", "latex"],
    thesisStages: ["defend"],
    url: "https://ctan.org/pkg/beamer",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "presentations",
    description:
      "Generates a full deck from a prompt or a pasted document, editable card by card.",
    featured: true,
    id: "gamma",
    isOpenSource: false,
    name: "Gamma",
    note: "Free plan gives 400 one-time credits and a watermark; PowerPoint export flattens layouts.",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "deck", "ai", "generator"],
    thesisStages: ["defend"],
    url: "https://gamma.app",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    brandIcon: "Microsoft PowerPoint",
    category: "presentations",
    description:
      "Drafts a deck from a prompt or a Word file inside PowerPoint itself.",
    id: "copilot-in-powerpoint",
    isOpenSource: false,
    name: "Copilot in PowerPoint",
    note: "Included with Microsoft 365 Personal and Family plans; check what the university Microsoft 365 plan includes.",
    platform: ["desktop", "web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "deck", "ai", "powerpoint"],
    thesisStages: ["defend"],
    url: "https://www.microsoft.com/en-us/microsoft-365/copilot",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    brandIcon: "Gemini",
    category: "presentations",
    description: "Generates slides and images in the Slides side panel.",
    id: "gemini-in-google-slides",
    isOpenSource: false,
    name: "Gemini in Google Slides",
    note: "Needs a Google AI plan or an eligible Workspace plan; the free Gemini app does not include it.",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "deck", "ai"],
    url: "https://workspace.google.com/products/slides",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "presentations",
    description:
      "Prompt to deck with brand-consistent templates and PowerPoint export.",
    id: "presentations-ai",
    isOpenSource: false,
    name: "Presentations.AI",
    note: "Starter plan gives 100 credits and up to 20 slides per deck.",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "deck", "ai", "generator"],
    url: "https://www.presentations.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "presentations",
    description: "Google Slides add-on that turns pasted text into slides.",
    id: "slidesai",
    isOpenSource: false,
    name: "SlidesAI",
    note: "Free plan allows 12 presentations a year with a short input limit.",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "ai", "google slides"],
    url: "https://www.slidesai.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Pitch",
    category: "presentations",
    description:
      "Collaborative deck editor with AI drafting and PowerPoint export.",
    id: "pitch",
    isOpenSource: false,
    name: "Pitch",
    note: "Free plan includes unlimited presentations and 100 one-time AI credits.",
    platform: ["web", "desktop"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "deck", "collaboration"],
    thesisStages: ["defend"],
    url: "https://pitch.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "trial",
    category: "presentations",
    description: "Smart templates that keep layouts tidy as you add content.",
    id: "beautiful-ai",
    isOpenSource: false,
    name: "Beautiful.ai",
    note: "No free plan; a short trial, then from about $15 a month billed yearly.",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "deck", "ai"],
    url: "https://www.beautiful.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "trial",
    category: "presentations",
    description:
      "AI slide generation inside Google Slides and PowerPoint, so nothing needs exporting.",
    id: "plus-ai",
    isOpenSource: false,
    name: "Plus AI",
    note: "No free plan; a short trial, then from about $20 a month.",
    platform: ["web", "desktop"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "ai", "google slides", "powerpoint"],
    url: "https://plusai.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "presentations",
    description: "Zooming, non-linear presentations with an AI first draft.",
    id: "prezi",
    isOpenSource: false,
    name: "Prezi",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "deck", "ai"],
    url: "https://prezi.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "presentations",
    description: "Agent that researches a topic and returns a finished deck.",
    id: "genspark-slides",
    isOpenSource: false,
    name: "Genspark AI Slides",
    note: "Daily free credits; a full deck can use most of them.",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["slides", "deck", "ai", "agent"],
    url: "https://www.genspark.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "presentations",
    description: "Turns a paragraph into a diagram or infographic for a slide.",
    id: "napkin",
    isOpenSource: false,
    name: "Napkin",
    note: "Free plan has weekly AI credits with PNG and PDF export.",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["visuals", "diagram", "ai", "slides"],
    thesisStages: ["defend"],
    url: "https://www.napkin.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "presentations",
    description:
      "Free Google Slides and PowerPoint templates, plus an AI deck maker.",
    id: "slidesgo",
    isOpenSource: false,
    name: "Slidesgo",
    platform: ["web"],
    tags: ["templates", "slides", "ai"],
    url: "https://slidesgo.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "presentations",
    description:
      "Markdown slides for developers with live code, Vue components, and PDF or PPTX export.",
    id: "slidev",
    isOpenSource: true,
    name: "Slidev",
    platform: ["cli"],
    tags: ["slides", "markdown", "code"],
    thesisStages: ["defend"],
    url: "https://sli.dev",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "presentations",
    description:
      "HTML presentation framework with fine control over transitions and layout.",
    id: "reveal-js",
    isOpenSource: true,
    name: "reveal.js",
    platform: ["library"],
    tags: ["slides", "html"],
    url: "https://revealjs.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
