import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const PRODUCTIVITY: Resource[] = [
  {
    access: "freemium",
    brandIcon: "Notion",
    category: "productivity",
    description:
      "Notes, databases, and boards in one workspace. Free Plus plan for students.",
    featured: true,
    id: "notion",
    isOpenSource: false,
    name: "Notion",
    platform: ["web", "desktop"],
    requiresAccount: true,
    tags: ["notes", "kanban", "wiki"],
    thesisStages: ["defend"],
    url: "https://www.notion.so",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Obsidian",
    category: "productivity",
    description:
      "Local Markdown notes with backlinks; pairs with a Zotero export.",
    id: "obsidian",
    isOpenSource: false,
    name: "Obsidian",
    note: "Sync is the paid part; the editor is free.",
    platform: ["desktop"],
    tags: ["notes", "markdown"],
    thesisStages: ["screen"],
    url: "https://obsidian.md",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "productivity",
    description: "Outliner notes with backlinks, local first.",
    id: "logseq",
    isOpenSource: true,
    name: "Logseq",
    platform: ["desktop"],
    tags: ["notes", "markdown"],
    url: "https://logseq.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "productivity",
    description: "Markdown notes with encrypted sync.",
    id: "joplin",
    isOpenSource: true,
    name: "Joplin",
    platform: ["desktop"],
    tags: ["notes", "markdown"],
    url: "https://joplinapp.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Microsoft OneNote",
    category: "productivity",
    description: "Digital notebook, good for handwritten notes.",
    id: "onenote",
    isOpenSource: false,
    name: "OneNote",
    platform: ["web", "desktop"],
    requiresAccount: true,
    tags: ["notes"],
    url: "https://www.onenote.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Trello",
    category: "productivity",
    description: "Kanban boards for tasks and milestones.",
    featured: true,
    id: "trello",
    isOpenSource: false,
    name: "Trello",
    platform: ["web"],
    requiresAccount: true,
    tags: ["kanban", "tasks"],
    thesisStages: ["defend"],
    url: "https://trello.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Linear",
    category: "productivity",
    description: "Issue tracking for technical projects.",
    id: "linear",
    isOpenSource: false,
    name: "Linear",
    platform: ["web"],
    requiresAccount: true,
    tags: ["issues", "tasks"],
    url: "https://linear.app",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "Todoist",
    category: "productivity",
    description: "Task and deadline management.",
    id: "todoist",
    isOpenSource: false,
    name: "Todoist",
    platform: ["web", "desktop"],
    requiresAccount: true,
    tags: ["tasks"],
    url: "https://todoist.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    brandIcon: "GitHub",
    category: "productivity",
    description: "Kanban tied to repository issues.",
    id: "github-projects",
    isOpenSource: false,
    name: "GitHub Projects",
    platform: ["web"],
    requiresAccount: true,
    tags: ["kanban", "issues"],
    thesisStages: ["defend"],
    url: "https://docs.github.com/en/issues/planning-and-tracking-with-projects",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "productivity",
    description:
      "Desktop Gantt and earned value, a Microsoft Project alternative.",
    featured: true,
    id: "projectlibre",
    isOpenSource: true,
    name: "ProjectLibre",
    platform: ["desktop"],
    tags: ["gantt", "project management"],
    thesisStages: ["defend"],
    url: "https://www.projectlibre.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "productivity",
    description: "Desktop scheduling with critical path.",
    id: "ganttproject",
    isOpenSource: true,
    name: "GanttProject",
    platform: ["desktop"],
    tags: ["gantt", "project management"],
    thesisStages: ["defend"],
    url: "https://www.ganttproject.biz",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "productivity",
    description: "Web project tracking with roadmaps and work packages.",
    id: "openproject",
    isOpenSource: true,
    name: "OpenProject",
    platform: ["web"],
    tags: ["project management", "self-hosted"],
    thesisStages: ["defend"],
    url: "https://www.openproject.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "productivity",
    description: "Time tracking for project management coursework.",
    id: "clockify",
    isOpenSource: false,
    name: "Clockify",
    platform: ["web"],
    requiresAccount: true,
    tags: ["time tracking"],
    url: "https://clockify.me",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Google Calendar",
    category: "productivity",
    description: "Deadlines and schedules.",
    id: "google-calendar",
    isOpenSource: false,
    name: "Google Calendar",
    platform: ["web"],
    requiresAccount: true,
    tags: ["calendar"],
    url: "https://calendar.google.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "productivity",
    description: "Collaborative Markdown for shared notes and minutes.",
    id: "hedgedoc",
    isOpenSource: true,
    name: "HedgeDoc",
    platform: ["web"],
    tags: ["notes", "markdown", "self-hosted"],
    url: "https://hedgedoc.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "productivity",
    description: "Pomodoro timer in the browser.",
    id: "pomofocus",
    isOpenSource: false,
    name: "Pomofocus",
    platform: ["web"],
    tags: ["timer"],
    url: "https://pomofocus.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
