import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const REFERENCES: Resource[] = [
  {
    access: "free",
    category: "references",
    description:
      "Browser capture, PDF notes, group libraries for supervisor sharing.",
    featured: true,
    id: "zotero",
    isOpenSource: true,
    name: "Zotero",
    platform: ["desktop"],
    tags: ["reference", "citation", "bibtex"],
    thesisStages: ["screen", "cite"],
    url: "https://www.zotero.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["BBT"],
    category: "references",
    description: "Stable citation keys and automatic BibTeX export.",
    featured: true,
    id: "zotero-better-bibtex",
    isOpenSource: true,
    name: "Better BibTeX for Zotero",
    platform: ["desktop"],
    tags: ["bibtex", "zotero", "plugin"],
    thesisStages: ["cite"],
    url: "https://retorquere.github.io/zotero-better-bibtex",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "references",
    description: "BibTeX-native manager for LaTeX-only manuscripts.",
    featured: true,
    id: "jabref",
    isOpenSource: true,
    name: "JabRef",
    platform: ["desktop"],
    tags: ["bibtex", "reference"],
    thesisStages: ["cite"],
    url: "https://www.jabref.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "references",
    description:
      "PDF annotation and collaboration; pick it when the advisor uses it.",
    id: "mendeley",
    isOpenSource: false,
    name: "Mendeley",
    platform: ["desktop", "web"],
    requiresAccount: true,
    tags: ["reference", "annotation"],
    thesisStages: ["cite"],
    url: "https://www.mendeley.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    category: "references",
    description:
      "Reference manager often bundled with a university library subscription.",
    id: "endnote",
    isOpenSource: false,
    name: "EndNote",
    platform: ["desktop", "web"],
    tags: ["reference"],
    url: "https://endnote.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "references",
    description: "One-off bibliography without a library.",
    id: "zoterobib",
    isOpenSource: false,
    name: "ZoteroBib",
    platform: ["web"],
    tags: ["bibliography", "citation"],
    thesisStages: ["cite"],
    url: "https://zbib.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "references",
    description: "DOI metadata lookup and validation.",
    id: "crossref",
    isOpenSource: false,
    name: "Crossref",
    platform: ["web"],
    tags: ["doi", "metadata"],
    thesisStages: ["cite"],
    url: "https://www.crossref.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "references",
    description: "Canonical DOI resolution check before submission.",
    id: "doi-org",
    isOpenSource: false,
    name: "DOI.org",
    platform: ["web"],
    tags: ["doi"],
    thesisStages: ["cite"],
    url: "https://doi.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "references",
    description: "Fetches and verifies DOIs for imported items.",
    id: "zotero-shortdoi",
    isOpenSource: true,
    name: "Zotero DOI Manager",
    platform: ["desktop"],
    tags: ["doi", "zotero", "plugin"],
    thesisStages: ["cite"],
    url: "https://github.com/bwiernik/zotero-shortdoi",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
