import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const REVIEW: Resource[] = [
  {
    access: "free",
    category: "review",
    description: "The reporting standard a review chapter is judged against.",
    id: "prisma-2020",
    isOpenSource: false,
    name: "PRISMA 2020",
    platform: ["reference"],
    tags: ["prisma", "standard"],
    thesisStages: ["screen"],
    url: "https://www.prisma-statement.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "review",
    description: "Active learning that ranks abstracts by relevance.",
    featured: true,
    id: "asreview",
    isOpenSource: true,
    name: "ASReview",
    platform: ["desktop"],
    tags: ["screening", "active learning"],
    thesisStages: ["screen"],
    url: "https://asreview.nl",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "review",
    description: "Collaborative blind screening with duplicate detection.",
    featured: true,
    id: "rayyan",
    isOpenSource: false,
    name: "Rayyan",
    platform: ["web"],
    requiresAccount: true,
    tags: ["screening"],
    thesisStages: ["screen"],
    url: "https://www.rayyan.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "review",
    description:
      "Docker workbench for the full Kitchenham workflow with PRISMA output.",
    featured: true,
    id: "reviq",
    isOpenSource: true,
    name: "ReviQ",
    platform: ["desktop"],
    status: "experimental",
    tags: ["screening", "prisma", "self-hosted"],
    thesisStages: ["screen"],
    url: "https://github.com/philipphaindl/ReviQ",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "review",
    description: "Protocol-driven review workspace.",
    id: "parsifal",
    isOpenSource: false,
    name: "Parsifal",
    platform: ["web"],
    requiresAccount: true,
    tags: ["screening", "protocol"],
    thesisStages: ["screen"],
    url: "https://parsif.al",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "review",
    description: "Multi-reviewer screening with conflict resolution.",
    id: "relis",
    isOpenSource: true,
    name: "ReLiS",
    platform: ["web"],
    tags: ["screening"],
    thesisStages: ["screen"],
    url: "https://relis.iro.umontreal.ca",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "review",
    description: "Web review tool with Crossref snowballing.",
    id: "thoth",
    isOpenSource: false,
    name: "Thoth",
    platform: ["web"],
    tags: ["screening", "snowballing"],
    thesisStages: ["screen"],
    url: "https://thoth-slr.com",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "review",
    description: "Git-native review loop across search, dedupe, and synthesis.",
    id: "colrev",
    isOpenSource: true,
    name: "ColRev",
    platform: ["cli"],
    tags: ["screening", "git"],
    thesisStages: ["screen"],
    url: "https://github.com/CoLRev-Environment/colrev",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "review",
    description: "Review coordination with evidence mapping.",
    id: "cadima",
    isOpenSource: false,
    name: "CADIMA",
    platform: ["web"],
    requiresAccount: true,
    tags: ["screening", "evidence"],
    thesisStages: ["screen"],
    url: "https://www.cadima.info",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "paid",
    category: "review",
    description: "Team screening platform, often institutional.",
    id: "covidence",
    isOpenSource: false,
    name: "Covidence",
    platform: ["web"],
    tags: ["screening"],
    url: "https://www.covidence.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "review",
    description: "The methodological guide for reviews in computing.",
    id: "kitchenham-guidelines",
    isOpenSource: false,
    name: "Kitchenham and Charters guidelines",
    platform: ["reference"],
    tags: ["method", "guide"],
    thesisStages: ["screen"],
    url: "https://www.cs.auckland.ac.nz/~mriaz/SE4Research/papers/Kitchenham.pdf",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "review",
    description: "Desktop review tool for software engineering.",
    id: "start",
    isOpenSource: false,
    name: "StArt",
    platform: ["desktop"],
    tags: ["screening"],
    url: "http://lapes.dc.ufscar.br/tools/start_tool",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
