import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const SATELLITE: Resource[] = [
  {
    access: "free",
    category: "satellite",
    description:
      "Link budgets, DVB-S2 ModCods, and ITU-R propagation in Python.",
    featured: true,
    id: "opensatcom",
    isOpenSource: true,
    name: "opensatcom",
    platform: ["library"],
    tags: ["link budget", "python"],
    url: "https://github.com/jman4162/opensatcom",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Probabilistic link margins with ITU-R rain and gas models.",
    id: "rftools-sat-link-budget",
    isOpenSource: false,
    name: "RF Tools satellite link budget",
    platform: ["web"],
    tags: ["link budget", "calculator"],
    url: "https://rftools.io/tools/sat-link-budget",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Real-time tracking and pass prediction with rotator control.",
    featured: true,
    id: "gpredict",
    isOpenSource: true,
    name: "Gpredict",
    platform: ["desktop"],
    tags: ["tracking", "passes"],
    url: "https://oz9aec.dk/gpredict",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description:
      "Python pass prediction and orbital geometry on JPL ephemerides.",
    featured: true,
    id: "skyfield",
    isOpenSource: true,
    name: "Skyfield",
    platform: ["library"],
    tags: ["tracking", "python", "orbit"],
    url: "https://rhodesmill.org/skyfield",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "The SGP4 propagator behind most tracking tools.",
    id: "python-sgp4",
    isOpenSource: true,
    name: "python-sgp4",
    platform: ["library"],
    tags: ["orbit", "python"],
    url: "https://github.com/brandon-rhodes/python-sgp4",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Coordinates, time, and units for space work.",
    id: "astropy",
    isOpenSource: true,
    name: "Astropy",
    platform: ["library"],
    tags: ["python", "astronomy"],
    url: "https://www.astropy.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["GMAT"],
    category: "satellite",
    description: "Mission design and trajectory optimisation.",
    id: "nasa-gmat",
    isOpenSource: true,
    name: "NASA GMAT",
    platform: ["desktop"],
    tags: ["mission", "orbit"],
    url: "https://software.nasa.gov/software/GSC-17177-1",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Open ground station network and client.",
    featured: true,
    id: "satnogs",
    isOpenSource: true,
    name: "SatNOGS",
    platform: ["web", "desktop"],
    tags: ["ground station"],
    url: "https://satnogs.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description:
      "GNU Radio telemetry decoders for CubeSat and science missions.",
    featured: true,
    id: "gr-satellites",
    isOpenSource: true,
    name: "gr-satellites",
    platform: ["library"],
    tags: ["decoder", "gnu radio"],
    url: "https://github.com/daniestevez/gr-satellites",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Decoder suite for weather and amateur downlinks.",
    id: "satdump",
    isOpenSource: true,
    name: "SatDump",
    platform: ["desktop"],
    tags: ["decoder"],
    url: "https://www.satdump.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Windows tracking for pass planning.",
    id: "orbitron",
    isOpenSource: false,
    name: "Orbitron",
    note: "Windows only.",
    platform: ["desktop"],
    tags: ["tracking"],
    url: "http://www.stoff.pl",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Two-line element sets for propagators.",
    id: "celestrak",
    isOpenSource: false,
    name: "CelesTrak",
    platform: ["dataset"],
    tags: ["tle", "data"],
    url: "https://celestrak.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Official US catalog, free after registration.",
    id: "space-track",
    isOpenSource: false,
    name: "Space-Track",
    platform: ["dataset"],
    requiresAccount: true,
    tags: ["tle", "data"],
    url: "https://www.space-track.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["cFS"],
    category: "satellite",
    description: "Core Flight System used on real spacecraft.",
    id: "nasa-cfs",
    isOpenSource: true,
    name: "NASA cFS",
    platform: ["library"],
    tags: ["flight software"],
    url: "https://github.com/nasa/cFS",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["SPICE"],
    category: "satellite",
    description: "Observation geometry for mission planning.",
    id: "nasa-spice",
    isOpenSource: false,
    name: "NASA SPICE Toolkit",
    platform: ["library"],
    tags: ["geometry", "mission"],
    url: "https://naif.jpl.nasa.gov/naif/toolkit.html",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "satellite",
    description: "Flight dynamics library for precise propagation.",
    id: "orekit",
    isOpenSource: true,
    name: "Orekit",
    platform: ["library"],
    tags: ["orbit", "java"],
    url: "https://www.orekit.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
