import { SECURITY_USE_NOTE } from "@/config/resources/copy";
import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const SECURITY: Resource[] = [
  {
    access: "free",
    category: "security",
    description: "Encode, decode, hash, and inspect data in the browser.",
    featured: true,
    id: "cyberchef",
    isOpenSource: true,
    name: "CyberChef",
    platform: ["web"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["encoding", "crypto"],
    url: "https://gchq.github.io/CyberChef",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Challenges built around real ciphers and constructions.",
    featured: true,
    id: "cryptohack",
    isOpenSource: false,
    name: "CryptoHack",
    platform: ["web"],
    privacyNote: SECURITY_USE_NOTE,
    requiresAccount: true,
    tags: ["crypto", "challenges"],
    url: "https://cryptohack.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Visual cipher and cryptanalysis lab.",
    id: "cryptool",
    isOpenSource: true,
    name: "CrypTool",
    platform: ["desktop", "web"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["crypto", "learning"],
    url: "https://www.cryptool.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "security",
    description: "Guided rooms for early security practice.",
    featured: true,
    id: "tryhackme",
    isOpenSource: false,
    name: "TryHackMe",
    platform: ["web"],
    privacyNote: SECURITY_USE_NOTE,
    requiresAccount: true,
    tags: ["practice", "labs"],
    url: "https://tryhackme.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    aliases: ["HTB"],
    brandIcon: "Hack The Box",
    category: "security",
    description: "Unguided labs for stronger students.",
    id: "hack-the-box",
    isOpenSource: false,
    name: "Hack The Box",
    platform: ["web"],
    privacyNote: SECURITY_USE_NOTE,
    requiresAccount: true,
    tags: ["practice", "labs"],
    url: "https://www.hackthebox.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Linux and security wargames.",
    id: "overthewire",
    isOpenSource: false,
    name: "OverTheWire",
    platform: ["web"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["practice", "wargames"],
    url: "https://overthewire.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Web security training labs.",
    id: "portswigger-academy",
    isOpenSource: false,
    name: "PortSwigger Web Security Academy",
    platform: ["web"],
    privacyNote: SECURITY_USE_NOTE,
    requiresAccount: true,
    tags: ["web security", "labs"],
    url: "https://portswigger.net/web-security",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "security",
    description: "Internet-connected device reconnaissance.",
    id: "shodan",
    isOpenSource: false,
    name: "Shodan",
    platform: ["web"],
    privacyNote: SECURITY_USE_NOTE,
    requiresAccount: true,
    tags: ["recon"],
    url: "https://www.shodan.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["HIBP"],
    category: "security",
    description: "Breach lookup for security awareness.",
    id: "have-i-been-pwned",
    isOpenSource: false,
    name: "Have I Been Pwned",
    platform: ["web"],
    tags: ["breach", "awareness"],
    url: "https://haveibeenpwned.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Top 10, testing guide, and threat modelling references.",
    featured: true,
    id: "owasp",
    isOpenSource: false,
    name: "OWASP",
    platform: ["reference"],
    tags: ["reference", "web security"],
    url: "https://owasp.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["ZAP"],
    category: "security",
    description: "Web application scanner for lab apps.",
    featured: true,
    id: "owasp-zap",
    isOpenSource: true,
    name: "OWASP ZAP",
    platform: ["desktop"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["scanner", "web security"],
    url: "https://www.zaproxy.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Burp"],
    category: "security",
    description: "Manual web testing with an intercepting proxy.",
    id: "burp-suite-community",
    isOpenSource: false,
    name: "Burp Suite Community",
    platform: ["desktop"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["proxy", "web security"],
    url: "https://portswigger.net/burp/communitydownload",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Host and service discovery. Custom NPSL license.",
    id: "nmap",
    isOpenSource: true,
    name: "Nmap",
    note: "Nmap Public Source License, not an OSI licence; read it before redistributing.",
    platform: ["cli"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["scanner", "recon"],
    url: "https://nmap.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Security distribution that bundles the lab tools.",
    id: "kali-linux",
    isOpenSource: true,
    name: "Kali Linux",
    platform: ["desktop"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["linux", "distribution"],
    url: "https://www.kali.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description:
      "TLS and core primitives, the reference for protocol experiments.",
    featured: true,
    id: "openssl",
    isOpenSource: true,
    name: "OpenSSL",
    platform: ["library"],
    tags: ["tls", "crypto"],
    url: "https://www.openssl.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Python primitives with safe defaults.",
    id: "pyca-cryptography",
    isOpenSource: true,
    name: "pyca/cryptography",
    platform: ["library"],
    tags: ["crypto", "python"],
    url: "https://cryptography.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Misuse-resistant crypto library.",
    id: "libsodium",
    isOpenSource: true,
    name: "libsodium",
    platform: ["library"],
    tags: ["crypto", "c"],
    url: "https://libsodium.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Post-quantum algorithms for advanced crypto work.",
    id: "liboqs",
    isOpenSource: true,
    name: "liboqs",
    platform: ["library"],
    tags: ["crypto", "post-quantum"],
    url: "https://openquantumsafe.org/liboqs",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Rule-based hash auditing.",
    id: "hashcat",
    isOpenSource: true,
    name: "Hashcat",
    platform: ["cli"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["passwords", "hashing"],
    url: "https://hashcat.net/hashcat",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Password strength auditing.",
    id: "john-the-ripper",
    isOpenSource: true,
    name: "John the Ripper",
    platform: ["cli"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["passwords"],
    url: "https://www.openwall.com/john",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Reverse engineering suite.",
    id: "ghidra",
    isOpenSource: true,
    name: "Ghidra",
    platform: ["desktop"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["reverse engineering"],
    url: "https://ghidra-sre.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Cutter"],
    category: "security",
    description: "Scriptable reverse engineering with a GUI.",
    id: "radare2",
    isOpenSource: true,
    name: "radare2 and Cutter",
    platform: ["desktop", "cli"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["reverse engineering"],
    url: "https://rada.re",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Exploit development library for binary analysis work.",
    featured: true,
    id: "pwntools",
    isOpenSource: true,
    name: "pwntools",
    platform: ["library"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["exploitation", "ctf", "python"],
    url: "https://docs.pwntools.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Turns traffic into structured security logs.",
    featured: true,
    id: "zeek",
    isOpenSource: true,
    name: "Zeek",
    platform: ["desktop"],
    tags: ["monitoring", "ids"],
    url: "https://zeek.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Intrusion detection and prevention engine.",
    featured: true,
    id: "suricata",
    isOpenSource: true,
    name: "Suricata",
    platform: ["desktop"],
    tags: ["ids", "ips"],
    url: "https://suricata.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Host and log monitoring with compliance reporting.",
    featured: true,
    id: "wazuh",
    isOpenSource: true,
    name: "Wazuh",
    platform: ["desktop"],
    tags: ["siem", "monitoring"],
    url: "https://wazuh.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "security",
    description: "Static analysis for insecure code patterns.",
    id: "semgrep",
    isOpenSource: true,
    name: "Semgrep",
    platform: ["cli"],
    requiresAccount: true,
    tags: ["static analysis"],
    url: "https://semgrep.dev",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Vulnerability scanning for containers and lock files.",
    id: "trivy",
    isOpenSource: true,
    name: "Trivy",
    platform: ["cli"],
    tags: ["scanner", "containers"],
    url: "https://trivy.dev",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Secret scanning across git history.",
    id: "gitleaks",
    isOpenSource: true,
    name: "gitleaks",
    platform: ["cli"],
    tags: ["secrets", "git"],
    url: "https://gitleaks.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Keycloak",
    category: "security",
    description: "Identity and access management with OIDC.",
    id: "keycloak",
    isOpenSource: true,
    name: "Keycloak",
    platform: ["desktop"],
    tags: ["iam", "oidc"],
    url: "https://www.keycloak.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Interactive HTTPS proxy for trust experiments.",
    id: "mitmproxy",
    isOpenSource: true,
    name: "mitmproxy",
    platform: ["cli"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["proxy", "https"],
    url: "https://mitmproxy.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description:
      "Penetration testing framework, the reference for offensive labs.",
    id: "metasploit",
    isOpenSource: true,
    name: "Metasploit",
    platform: ["desktop", "cli"],
    privacyNote: SECURITY_USE_NOTE,
    tags: ["pentest", "framework"],
    url: "https://www.metasploit.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "security",
    description: "Pattern matching for malware classification.",
    id: "yara",
    isOpenSource: true,
    name: "YARA",
    platform: ["cli"],
    tags: ["malware", "patterns"],
    url: "https://virustotal.github.io/yara",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
