import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const THESIS_ARCHIVES: Resource[] = [
  {
    access: "free",
    aliases: ["Open Access Theses and Dissertations"],
    category: "thesis-archives",
    description: "Open access theses and dissertations worldwide.",
    featured: true,
    id: "oatd",
    isOpenSource: false,
    name: "OATD",
    platform: ["web"],
    tags: ["theses"],
    thesisStages: ["prior-theses"],
    url: "https://oatd.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "thesis-archives",
    description: "Global thesis library network.",
    featured: true,
    id: "ndltd",
    isOpenSource: false,
    name: "NDLTD",
    platform: ["web"],
    tags: ["theses"],
    thesisStages: ["prior-theses"],
    url: "https://ndltd.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "thesis-archives",
    description: "Open dissertation index with faceted search.",
    id: "ebsco-open-dissertations",
    isOpenSource: false,
    name: "EBSCO Open Dissertations",
    platform: ["web"],
    tags: ["theses"],
    thesisStages: ["prior-theses"],
    url: "https://opendissertations.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "thesis-archives",
    description: "European thesis portal with full text.",
    id: "dart-europe",
    isOpenSource: false,
    name: "DART-Europe",
    platform: ["web"],
    tags: ["theses"],
    thesisStages: ["prior-theses"],
    url: "https://www.dart-europe.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "thesis-archives",
    description: "Links publications, data, and funding.",
    id: "openaire",
    isOpenSource: false,
    name: "OpenAIRE",
    platform: ["web"],
    tags: ["open access"],
    thesisStages: ["prior-theses"],
    url: "https://www.openaire.eu",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "thesis-archives",
    description: "Institutional repository content across universities.",
    id: "digital-commons-network",
    isOpenSource: false,
    name: "Digital Commons Network",
    platform: ["web"],
    tags: ["open access", "repositories"],
    thesisStages: ["prior-theses"],
    url: "https://network.bepress.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "thesis-archives",
    description: "French open archive, strong in European research.",
    id: "hal",
    isOpenSource: false,
    name: "HAL",
    platform: ["web"],
    tags: ["open access"],
    thesisStages: ["prior-theses"],
    url: "https://hal.science",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
