import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const VISION: Resource[] = [
  {
    access: "free",
    category: "vision",
    description: "The base vision library and its tutorials.",
    featured: true,
    id: "opencv",
    isOpenSource: true,
    name: "OpenCV",
    platform: ["library"],
    tags: ["vision", "python", "c++"],
    thesisStages: ["experiment"],
    url: "https://opencv.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["skimage"],
    category: "vision",
    description: "NumPy-native image processing.",
    featured: true,
    id: "scikit-image",
    isOpenSource: true,
    name: "scikit-image",
    platform: ["library"],
    tags: ["image", "python"],
    url: "https://scikit-image.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Differentiable vision operators inside PyTorch.",
    id: "kornia",
    isOpenSource: true,
    name: "Kornia",
    platform: ["library"],
    tags: ["vision", "pytorch"],
    url: "https://kornia.readthedocs.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Fast augmentation with mask and box support.",
    id: "albumentations",
    isOpenSource: true,
    name: "Albumentations",
    platform: ["library"],
    tags: ["augmentation", "python"],
    url: "https://albumentations.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Annotation for boxes, polygons, text, and time series.",
    featured: true,
    id: "label-studio",
    isOpenSource: true,
    name: "Label Studio",
    platform: ["web"],
    tags: ["annotation", "labeling"],
    thesisStages: ["experiment"],
    url: "https://labelstud.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Self-hosted image and video annotation.",
    featured: true,
    id: "cvat",
    isOpenSource: true,
    name: "CVAT",
    platform: ["web"],
    tags: ["annotation", "labeling", "self-hosted"],
    thesisStages: ["experiment"],
    url: "https://www.cvat.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Voxel51"],
    category: "vision",
    description: "Dataset curation and model error analysis.",
    featured: true,
    id: "fiftyone",
    isOpenSource: true,
    name: "FiftyOne",
    platform: ["library"],
    tags: ["dataset", "curation"],
    thesisStages: ["experiment"],
    url: "https://voxel51.com/fiftyone",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "vision",
    description: "Hosted annotation and a fast path to a YOLO model.",
    id: "roboflow",
    isOpenSource: false,
    name: "Roboflow",
    platform: ["web"],
    requiresAccount: true,
    tags: ["annotation", "yolo"],
    url: "https://roboflow.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Browser annotation with no account.",
    id: "make-sense",
    isOpenSource: true,
    name: "Make Sense",
    platform: ["web"],
    tags: ["annotation"],
    url: "https://www.makesense.ai",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Polygon annotation in Python.",
    id: "labelme",
    isOpenSource: true,
    name: "labelme",
    platform: ["desktop"],
    tags: ["annotation", "python"],
    url: "https://github.com/wkentaro/labelme",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Reference detection models. AGPL applies to derived code.",
    id: "ultralytics-yolo",
    isOpenSource: true,
    name: "Ultralytics YOLO",
    note: "AGPL-3.0: a distributed derivative must publish its source.",
    platform: ["library"],
    tags: ["detection", "yolo"],
    url: "https://docs.ultralytics.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Meta's detection and segmentation framework.",
    id: "detectron2",
    isOpenSource: true,
    name: "Detectron2",
    platform: ["library"],
    tags: ["detection", "segmentation"],
    url: "https://github.com/facebookresearch/detectron2",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Open model zoo for detection research.",
    id: "mmdetection",
    isOpenSource: true,
    name: "MMDetection",
    platform: ["library"],
    tags: ["detection"],
    url: "https://mmdetection.readthedocs.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["SAM", "SAM 2"],
    category: "vision",
    description: "Promptable segmentation for building masks fast.",
    id: "segment-anything",
    isOpenSource: true,
    name: "Segment Anything",
    platform: ["library"],
    tags: ["segmentation"],
    url: "https://github.com/facebookresearch/sam2",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "vision",
    description: "Point cloud and 3D geometry processing.",
    id: "open3d",
    isOpenSource: true,
    name: "Open3D",
    platform: ["library"],
    tags: ["3d", "point cloud"],
    url: "https://www.open3d.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["Fiji"],
    category: "vision",
    description: "Scientific image analysis with a plugin ecosystem.",
    id: "imagej-fiji",
    isOpenSource: true,
    name: "ImageJ and Fiji",
    platform: ["desktop"],
    tags: ["image", "scientific"],
    url: "https://imagej.net/software/fiji",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["PIL"],
    category: "vision",
    description: "Image loading and preprocessing in Python.",
    id: "pillow",
    isOpenSource: true,
    name: "Pillow",
    platform: ["library"],
    tags: ["image", "python"],
    url: "https://python-pillow.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
