import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const WIRELESS: Resource[] = [
  {
    access: "free",
    aliases: ["Sionna RT"],
    brandIcon: "NVIDIA",
    category: "wireless",
    description:
      "GPU link-level simulator for 5G and 6G PHY, with ray tracing.",
    featured: true,
    id: "sionna",
    isOpenSource: true,
    name: "Sionna",
    platform: ["library"],
    tags: ["5g", "simulation", "python"],
    thesisStages: ["experiment"],
    url: "https://nvlabs.github.io/sionna",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description:
      "Minimal Python chain for QAM, AWGN, OFDM, MIMO, and BER curves.",
    featured: true,
    id: "comnumpy",
    isOpenSource: true,
    name: "comnumpy",
    platform: ["library"],
    tags: ["simulation", "python", "ber"],
    thesisStages: ["experiment"],
    url: "https://github.com/vincentchoqueuse/comnumpy",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Modulators, channels, and Viterbi decoding in Python.",
    id: "commpy",
    isOpenSource: true,
    name: "CommPy",
    platform: ["library"],
    tags: ["simulation", "python", "coding"],
    url: "https://github.com/veeresht/CommPy",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Fast C++ toolbox for LDPC, Turbo, Polar, and BCH codes.",
    id: "aff3ct",
    isOpenSource: true,
    name: "AFF3CT",
    platform: ["library"],
    tags: ["coding", "fec", "c++"],
    url: "https://aff3ct.github.io",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description:
      "PyTorch toolkit for learned communications and joint source-channel coding.",
    id: "kaira",
    isOpenSource: true,
    name: "Kaira",
    platform: ["library"],
    tags: ["ml", "pytorch", "simulation"],
    thesisStages: ["experiment"],
    url: "https://github.com/ipc-lab/kaira",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description:
      "Ray-traced channel datasets that plug into Sionna and MATLAB.",
    id: "deepmimo",
    isOpenSource: false,
    name: "DeepMIMO",
    platform: ["dataset"],
    tags: ["dataset", "mimo", "channel"],
    thesisStages: ["experiment"],
    url: "https://www.deepmimo.net",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Synthetic RF datasets and signal classification in PyTorch.",
    id: "torchsig",
    isOpenSource: true,
    name: "TorchSig",
    platform: ["library"],
    tags: ["dataset", "ml", "rf"],
    url: "https://github.com/TorchDSP/torchsig",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Millimetre-wave channel simulator from NYU Wireless.",
    id: "nyusim",
    isOpenSource: false,
    name: "NYUSIM",
    platform: ["desktop"],
    requiresAccount: true,
    tags: ["channel", "mmwave", "simulation"],
    url: "https://wireless.engineering.nyu.edu/nyusim",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Quasi-deterministic MIMO channel generator with mobility.",
    id: "quadriga",
    isOpenSource: false,
    name: "QuaDRiGa",
    note: "Runs in MATLAB or Octave.",
    platform: ["library"],
    tags: ["channel", "mimo"],
    url: "https://quadriga-channel-model.de",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Open 5G RAN suite runnable on SDR hardware or in simulation.",
    featured: true,
    id: "srsran",
    isOpenSource: true,
    name: "srsRAN Project",
    platform: ["desktop"],
    tags: ["5g", "ran", "sdr"],
    url: "https://www.srsran.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "5G core and 4G EPC for end-to-end experiments.",
    featured: true,
    id: "open5gs",
    isOpenSource: true,
    name: "Open5GS",
    platform: ["desktop"],
    tags: ["5g", "core"],
    url: "https://open5gs.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["OAI"],
    category: "wireless",
    description:
      "3GPP-compliant RAN and core on commodity hardware. Setup cost is high.",
    id: "openairinterface",
    isOpenSource: true,
    name: "OpenAirInterface",
    platform: ["desktop"],
    tags: ["5g", "ran", "core"],
    url: "https://openairinterface.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "ns-3 module for 5G New Radio including mmWave.",
    id: "ns3-5g-lena",
    isOpenSource: true,
    name: "5G-LENA",
    platform: ["library"],
    tags: ["5g", "ns-3", "simulation"],
    url: "https://5g-lena.cttc.es",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "OMNeT++ library for 5G user and control plane.",
    id: "simu5g",
    isOpenSource: true,
    name: "Simu5G",
    platform: ["library"],
    tags: ["5g", "omnet++", "simulation"],
    url: "https://simu5g.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Open GSM, UMTS, and LTE stack components.",
    id: "osmocom",
    isOpenSource: true,
    name: "Osmocom",
    platform: ["desktop"],
    tags: ["gsm", "lte"],
    url: "https://osmocom.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "The primary standards; cite these, not a blog summary.",
    id: "3gpp-specs",
    isOpenSource: false,
    name: "3GPP specifications",
    platform: ["reference"],
    tags: ["standards", "reference"],
    url: "https://www.3gpp.org/specifications-technologies/specifications-3gpp",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Path loss, Fresnel zone, and link budget calculators.",
    id: "rf-wireless-world",
    isOpenSource: false,
    name: "RF Wireless World calculators",
    platform: ["web"],
    tags: ["calculator", "link budget"],
    url: "https://www.rfwireless-world.com/calculators",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Interactive Smith chart for impedance matching.",
    id: "smith-chart-tool",
    isOpenSource: false,
    name: "Smith Chart Tool",
    platform: ["web"],
    tags: ["rf", "impedance"],
    url: "https://www.will-kelsey.com/smith_chart",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "wireless",
    description: "Circuit simulation where comms theory meets hardware.",
    id: "ltspice",
    isOpenSource: false,
    name: "LTspice",
    platform: ["desktop"],
    tags: ["circuit", "simulation"],
    url: "https://www.analog.com/en/resources/design-tools-and-calculators/ltspice-simulator.html",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
