import { AI_PRIVACY_NOTE } from "@/config/resources/copy";
import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Resource } from "@/lib/resources/types";

export const WRITING: Resource[] = [
  {
    access: "freemium",
    category: "writing",
    description: "Collaborative LaTeX with templates and advisor comments.",
    featured: true,
    id: "overleaf",
    isOpenSource: false,
    name: "Overleaf",
    platform: ["web"],
    requiresAccount: true,
    tags: ["latex", "typesetting"],
    thesisStages: ["write"],
    url: "https://www.overleaf.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Fast typesetting with readable markup and clean math.",
    featured: true,
    id: "typst",
    isOpenSource: true,
    name: "Typst",
    platform: ["web", "cli"],
    tags: ["typesetting"],
    thesisStages: ["write"],
    url: "https://typst.app",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "One source to PDF, HTML, Word, and slides, code included.",
    featured: true,
    id: "quarto",
    isOpenSource: true,
    name: "Quarto",
    platform: ["cli"],
    tags: ["typesetting", "reproducibility", "markdown"],
    thesisStages: ["write", "analyse"],
    url: "https://quarto.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description:
      "Converts between Markdown, LaTeX, DOCX, and PDF with citations.",
    featured: true,
    id: "pandoc",
    isOpenSource: true,
    name: "Pandoc",
    platform: ["cli"],
    tags: ["converter", "markdown"],
    thesisStages: ["write"],
    url: "https://pandoc.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Structure-first editing over LaTeX.",
    id: "lyx",
    isOpenSource: true,
    name: "LyX",
    platform: ["desktop"],
    tags: ["latex", "editor"],
    thesisStages: ["write"],
    url: "https://www.lyx.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Full-featured desktop LaTeX editor.",
    id: "texstudio",
    isOpenSource: true,
    name: "TeXstudio",
    platform: ["desktop"],
    tags: ["latex", "editor"],
    thesisStages: ["write"],
    url: "https://www.texstudio.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    brandIcon: "Visual Studio Code",
    category: "writing",
    description: "VS Code extension for local LaTeX builds with SyncTeX.",
    id: "latex-workshop",
    isOpenSource: true,
    name: "LaTeX Workshop",
    platform: ["desktop"],
    tags: ["latex", "editor", "vscode"],
    thesisStages: ["write"],
    url: "https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    aliases: ["MiKTeX"],
    category: "writing",
    description: "Local LaTeX distribution for offline builds.",
    id: "tex-live",
    isOpenSource: true,
    name: "TeX Live",
    platform: ["desktop"],
    tags: ["latex"],
    thesisStages: ["write"],
    url: "https://tug.org/texlive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Official LaTeX documentation.",
    id: "latex-project",
    isOpenSource: true,
    name: "LaTeX Project",
    platform: ["reference"],
    tags: ["latex", "reference"],
    url: "https://www.latex-project.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Official IEEE manuscript templates.",
    id: "ieee-template-selector",
    isOpenSource: false,
    name: "IEEE Template Selector",
    platform: ["web"],
    tags: ["templates", "ieee"],
    thesisStages: ["frame", "write"],
    url: "https://template-selector.ieee.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Sentence patterns for reviews, methods, and limitations.",
    featured: true,
    id: "academic-phrasebank",
    isOpenSource: false,
    name: "Academic Phrasebank",
    platform: ["reference"],
    tags: ["phrasing", "writing"],
    thesisStages: ["write"],
    url: "https://www.phrasebank.manchester.ac.uk",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "writing",
    description: "Grammar and clarity checking.",
    id: "grammarly",
    isOpenSource: false,
    name: "Grammarly",
    platform: ["web", "desktop"],
    privacyNote: AI_PRIVACY_NOTE,
    requiresAccount: true,
    tags: ["grammar", "proofing"],
    thesisStages: ["write"],
    url: "https://www.grammarly.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "writing",
    description: "Grammar and style with a self-hosted option.",
    id: "languagetool",
    isOpenSource: true,
    name: "LanguageTool",
    platform: ["web", "desktop"],
    tags: ["grammar", "proofing", "self-hosted"],
    thesisStages: ["write"],
    url: "https://languagetool.org",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "writing",
    description: "Rephrasing polish for non-native English.",
    id: "deepl-write",
    isOpenSource: false,
    name: "DeepL Write",
    platform: ["web"],
    privacyNote: AI_PRIVACY_NOTE,
    tags: ["proofing", "rephrasing"],
    thesisStages: ["write"],
    url: "https://www.deepl.com/write",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "freemium",
    category: "writing",
    description: "Academic phrasing feedback.",
    id: "writefull",
    isOpenSource: false,
    name: "Writefull",
    platform: ["web"],
    requiresAccount: true,
    tags: ["proofing", "academic"],
    thesisStages: ["write"],
    url: "https://www.writefull.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Highlights long sentences and passive voice.",
    id: "hemingway",
    isOpenSource: false,
    name: "Hemingway Editor",
    platform: ["web"],
    tags: ["proofing", "readability"],
    thesisStages: ["write"],
    url: "https://hemingwayapp.com",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Markdown to slide deck, kept in version control.",
    id: "marp",
    isOpenSource: true,
    name: "Marp",
    platform: ["cli"],
    tags: ["slides", "markdown"],
    thesisStages: ["defend"],
    url: "https://marp.app",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "LaTeX slides that match the manuscript.",
    id: "beamer",
    isOpenSource: true,
    name: "Beamer",
    platform: ["library"],
    tags: ["slides", "latex"],
    thesisStages: ["defend"],
    url: "https://ctan.org/pkg/beamer",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Local-first LaTeX and Typst editor with offline builds.",
    id: "texlyre",
    isOpenSource: true,
    name: "TeXlyre",
    platform: ["web"],
    status: "experimental",
    tags: ["latex", "typst", "editor"],
    thesisStages: ["write"],
    url: "https://github.com/TeXlyre/texlyre",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description:
      "Local-first LaTeX, Typst, and Markdown workspace with Git history.",
    id: "oleafly",
    isOpenSource: true,
    name: "Oleafly",
    platform: ["desktop"],
    status: "experimental",
    tags: ["latex", "typst", "editor"],
    thesisStages: ["write"],
    url: "https://oleafly.com",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Self-hosted Overleaf alternative, CLI-first.",
    id: "tinyleaf",
    isOpenSource: true,
    name: "tinyleaf",
    platform: ["web"],
    status: "experimental",
    tags: ["latex", "editor", "self-hosted"],
    thesisStages: ["write"],
    url: "https://github.com/Oaklight/tinyleaf",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Browser LaTeX editor compiling client-side.",
    id: "texbrain",
    isOpenSource: true,
    name: "TeXbrain",
    platform: ["web"],
    status: "experimental",
    tags: ["latex", "editor"],
    thesisStages: ["write"],
    url: "https://github.com/swimmingbrain/texbrain",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Local-first LaTeX workspace with AI assistance.",
    id: "openprism",
    isOpenSource: true,
    name: "OpenPrism",
    platform: ["desktop"],
    privacyNote: AI_PRIVACY_NOTE,
    status: "experimental",
    tags: ["latex", "editor", "ai"],
    thesisStages: ["write"],
    url: "https://github.com/OpenDCAI/OpenPrism",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description:
      "Self-hosted collaborative LaTeX with tracked changes. Single maintainer.",
    id: "flowtex",
    isOpenSource: true,
    name: "FlowTex",
    platform: ["web"],
    status: "experimental",
    tags: ["latex", "editor", "self-hosted"],
    thesisStages: ["write"],
    url: "https://github.com/stolucc/flowtex",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Agent skill that walks a paper section by section.",
    id: "scholarly-writing-skill",
    isOpenSource: true,
    name: "Scholarly (writing skill)",
    platform: ["cli"],
    privacyNote: AI_PRIVACY_NOTE,
    status: "experimental",
    tags: ["ai", "writing"],
    thesisStages: ["write"],
    url: "https://github.com/ShiyangZheng/scholarly",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description:
      "Multi-agent draft generator with citation checks. A drafting aid, not a ghostwriter.",
    id: "opendraft",
    isOpenSource: true,
    name: "OpenDraft",
    note: "Check the department authorship rules before using AI-drafted text in a submission.",
    platform: ["cli"],
    privacyNote: AI_PRIVACY_NOTE,
    status: "experimental",
    tags: ["ai", "drafting"],
    thesisStages: ["write"],
    url: "https://github.com/PhilioAI/opendraft",
    verification: "pending",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    access: "free",
    category: "writing",
    description: "Autonomous research agent that returns a cited report.",
    id: "gpt-researcher",
    isOpenSource: true,
    name: "GPT Researcher",
    platform: ["cli"],
    privacyNote: AI_PRIVACY_NOTE,
    status: "experimental",
    tags: ["ai", "agent"],
    thesisStages: ["frame"],
    url: "https://gptr.dev",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
