export const MARQUEE_ITEMS: string[] = [
  "AUTO-SYNCED FROM DRIVE",
  "SEARCH BY COURSE OR SEMESTER",
  "TWO YEARS OF MATERIALS",
  "NO SIGN-IN REQUIRED",
  "LIU · MCCE",
  "PAST EXAMS · SLIDES · RECORDINGS",
  "GPA CALCULATOR ON THE 4.0 SCALE",
  "FULL PLAN OF STUDY",
  "WORKS OFFLINE",
  "EVERY FILE, ONE SEARCH AWAY",
];
