export const MARQUEE_ITEMS: string[] = [
  "AUTO-SYNCED FROM DRIVE",
  "SEARCH BY COURSE OR SEMESTER",
  "TWO YEARS OF MATERIALS",
  "NO SIGN-IN REQUIRED",
  "LIU · MCCE",
  "PAST EXAMS · SLIDES · RECORDINGS",
  "BUILT FOR THE PROGRAM",
  "EVERY FILE, ONE SEARCH AWAY",
];
