import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const ANALYSIS_REPOS: Repository[] = [
  {
    description: "Array computing.",
    domain: "analysis",
    id: "numpy-numpy",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "numpy",
    owner: "numpy",
    resourceId: "numpy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Scientific computing, home of scipy.signal.",
    domain: "analysis",
    id: "scipy-scipy",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "scipy",
    owner: "scipy",
    resourceId: "scipy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Dataframes.",
    domain: "analysis",
    id: "pandas-dev-pandas",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "pandas",
    owner: "pandas-dev",
    resourceId: "pandas",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Plotting.",
    domain: "analysis",
    id: "matplotlib-matplotlib",
    languages: ["Python"],
    license: "PSF-2.0",
    maintenance: "active",
    name: "matplotlib",
    owner: "matplotlib",
    resourceId: "matplotlib",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Statistical plots.",
    domain: "analysis",
    id: "mwaskom-seaborn",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "seaborn",
    owner: "mwaskom",
    resourceId: "seaborn",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Interactive figures.",
    domain: "analysis",
    id: "plotly-plotly-py",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "plotly.py",
    owner: "plotly",
    resourceId: "plotly",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "The notebook interface.",
    domain: "analysis",
    id: "jupyterlab-jupyterlab",
    languages: ["TypeScript"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "jupyterlab",
    owner: "jupyterlab",
    resourceId: "jupyter",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "GUI statistics.",
    domain: "analysis",
    id: "jasp-stats-jasp-desktop",
    languages: ["C++"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "jasp-desktop",
    owner: "jasp-stats",
    resourceId: "jasp",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "GUI statistics on R.",
    domain: "analysis",
    id: "jamovi-jamovi",
    languages: ["JavaScript"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "jamovi",
    owner: "jamovi",
    resourceId: "jamovi",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "MATLAB-compatible interpreter.",
    domain: "analysis",
    id: "gnu-octave-octave",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "octave",
    note: "GitHub mirror of the Savannah repository.",
    owner: "gnu-octave",
    resourceId: "gnu-octave",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Statistical models and tests.",
    domain: "analysis",
    id: "statsmodels-statsmodels",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "statsmodels",
    owner: "statsmodels",
    resourceId: "statsmodels",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Tests with effect sizes.",
    domain: "analysis",
    id: "raphaelvallat-pingouin",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "pingouin",
    owner: "raphaelvallat",
    resourceId: "pingouin",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Symbolic mathematics.",
    domain: "analysis",
    id: "sympy-sympy",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "sympy",
    owner: "sympy",
    resourceId: "sympy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Bayesian modelling bridge to Stan.",
    domain: "analysis",
    id: "stan-dev-cmdstanpy",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "cmdstanpy",
    owner: "stan-dev",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
