import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const COLLABORATION_REPOS: Repository[] = [
  {
    description: "Web project tracking.",
    domain: "collaboration",
    id: "opf-openproject",
    languages: ["Ruby"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "openproject",
    owner: "opf",
    resourceId: "openproject",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Issue tracking and backlog.",
    domain: "collaboration",
    id: "makeplane-plane",
    languages: ["TypeScript"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "plane",
    owner: "makeplane",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Agile backlog and sprints.",
    domain: "collaboration",
    id: "taigaio-taiga-back",
    languages: ["Python"],
    license: "AGPL-3.0",
    maintenance: "steady",
    name: "taiga-back",
    owner: "taigaio",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Issue tracking with Gantt.",
    domain: "collaboration",
    id: "redmine-redmine",
    languages: ["Ruby"],
    license: "GPL-2.0",
    maintenance: "steady",
    name: "redmine",
    owner: "redmine",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Desktop Gantt.",
    domain: "collaboration",
    id: "ganttproject-ganttproject",
    languages: ["Java"],
    license: "GPL-3.0",
    maintenance: "steady",
    name: "ganttproject",
    owner: "GanttProject",
    resourceId: "ganttproject",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Collaborative Markdown.",
    domain: "collaboration",
    id: "hedgedoc-hedgedoc",
    languages: ["TypeScript"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "hedgedoc",
    owner: "hedgedoc",
    resourceId: "hedgedoc",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Real-time collaborative editor.",
    domain: "collaboration",
    id: "ether-etherpad-lite",
    languages: ["JavaScript"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "etherpad-lite",
    owner: "ether",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Self-hosted Git forge.",
    domain: "collaboration",
    id: "go-gitea-gitea",
    languages: ["Go"],
    license: "MIT",
    maintenance: "active",
    name: "gitea",
    owner: "go-gitea",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Nextcloud, Mattermost, and Git lab workflow.",
    domain: "collaboration",
    id: "datadiversitylab-labops",
    languages: ["Shell"],
    license: "custom",
    maintenance: "steady",
    name: "LabOps",
    owner: "datadiversitylab",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
