import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const DATA_MINING_REPOS: Repository[] = [
  {
    description: "Rust dataframe.",
    domain: "data-mining",
    id: "pola-rs-polars",
    languages: ["Rust"],
    license: "MIT",
    maintenance: "active",
    name: "polars",
    owner: "pola-rs",
    resourceId: "polars",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "In-process analytical SQL.",
    domain: "data-mining",
    id: "duckdb-duckdb",
    languages: ["C++"],
    license: "MIT",
    maintenance: "active",
    name: "duckdb",
    owner: "duckdb",
    resourceId: "duckdb",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Columnar format.",
    domain: "data-mining",
    id: "apache-arrow",
    languages: ["C++"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "arrow",
    owner: "apache",
    resourceId: "apache-arrow",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Parallel pandas and NumPy.",
    domain: "data-mining",
    id: "dask-dask",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "dask",
    owner: "dask",
    resourceId: "dask",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Distributed processing.",
    domain: "data-mining",
    id: "apache-spark",
    languages: ["Scala"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "spark",
    owner: "apache",
    resourceId: "apache-spark",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Association rules and stacking.",
    domain: "data-mining",
    id: "rasbt-mlxtend",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "mlxtend",
    owner: "rasbt",
    resourceId: "mlxtend",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Low-code model comparison.",
    domain: "data-mining",
    id: "pycaret-pycaret",
    languages: ["Python"],
    license: "MIT",
    maintenance: "steady",
    name: "pycaret",
    owner: "pycaret",
    resourceId: "pycaret",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Dataset profiling.",
    domain: "data-mining",
    id: "ydataai-ydata-profiling",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "ydata-profiling",
    owner: "ydataai",
    resourceId: "ydata-profiling",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Data quality assertions.",
    domain: "data-mining",
    id: "great-expectations-great-expectations",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "great_expectations",
    owner: "great-expectations",
    resourceId: "great-expectations",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Visual data mining.",
    domain: "data-mining",
    id: "biolab-orange3",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "orange3",
    owner: "biolab",
    resourceId: "orange",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Clustering and outlier toolkit.",
    domain: "data-mining",
    id: "elki-project-elki",
    languages: ["Java"],
    license: "AGPL-3.0",
    maintenance: "steady",
    name: "elki",
    owner: "elki-project",
    resourceId: "elki",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
