import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const DSP_REPOS: Repository[] = [
  {
    description: "SDR framework.",
    domain: "dsp",
    id: "gnuradio-gnuradio",
    languages: ["C++", "Python"],
    license: "GPL-3.0-or-later",
    maintenance: "active",
    name: "gnuradio",
    owner: "gnuradio",
    resourceId: "gnu-radio",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Embedded-grade DSP in C.",
    domain: "dsp",
    id: "jgaeddert-liquid-dsp",
    languages: ["C"],
    license: "MIT",
    maintenance: "active",
    name: "liquid-dsp",
    owner: "jgaeddert",
    resourceId: "liquid-dsp",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Source for the PySDR textbook.",
    domain: "dsp",
    id: "777arc-pysdr",
    languages: ["Python"],
    license: "custom",
    maintenance: "active",
    name: "PySDR",
    note: "Owner to confirm; drafts cite pysdr/pysdr.",
    owner: "777arc",
    resourceId: "pysdr",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "GNU Radio blocks for SDR hardware.",
    domain: "dsp",
    id: "osmocom-gr-osmosdr",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "steady",
    name: "gr-osmosdr",
    note: "Mirror of the Osmocom Gitea; drafts cite a personal fork.",
    owner: "osmocom",
    resourceId: "gr-osmosdr",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Signal analyser.",
    domain: "dsp",
    id: "batchdrake-sigdigger",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "SigDigger",
    owner: "BatchDrake",
    resourceId: "sigdigger",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Light receiver.",
    domain: "dsp",
    id: "alexandrerouma-sdrplusplus",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "SDRPlusPlus",
    owner: "AlexandreRouma",
    resourceId: "sdrpp",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Full SDR application.",
    domain: "dsp",
    id: "f4exb-sdrangel",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "sdrangel",
    owner: "f4exb",
    resourceId: "sdrangel",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "IQ capture inspector.",
    domain: "dsp",
    id: "miek-inspectrum",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "steady",
    name: "inspectrum",
    owner: "miek",
    resourceId: "inspectrum",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Audio DSP.",
    domain: "dsp",
    id: "librosa-librosa",
    languages: ["Python"],
    license: "ISC",
    maintenance: "active",
    name: "librosa",
    note: "Drafts cite audiolabs/librosa; the org is librosa.",
    owner: "librosa",
    resourceId: "librosa",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Audio editor.",
    domain: "dsp",
    id: "audacity-audacity",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "audacity",
    owner: "audacity",
    resourceId: "audacity",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Functional DSP language.",
    domain: "dsp",
    id: "grame-cncm-faust",
    languages: ["C++"],
    license: "LGPL-2.1",
    maintenance: "active",
    name: "faust",
    owner: "grame-cncm",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Wavelet transforms.",
    domain: "dsp",
    id: "pywavelets-pywt",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "pywt",
    owner: "PyWavelets",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Teaching DSP and comms functions.",
    domain: "dsp",
    id: "mwickert-scikit-dsp-comm",
    languages: ["Python"],
    license: "BSD-2-Clause",
    maintenance: "steady",
    name: "scikit-dsp-comm",
    note: "Owner to confirm.",
    owner: "mwickert",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "C++ DSP framework.",
    domain: "dsp",
    id: "kfrlib-kfr",
    languages: ["C++"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "kfr",
    note: "Dual licensed; GPL for open use.",
    owner: "kfrlib",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "SDR hardware abstraction.",
    domain: "dsp",
    id: "pothosware-soapysdr",
    languages: ["C++"],
    license: "BSL-1.0",
    maintenance: "active",
    name: "SoapySDR",
    owner: "pothosware",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "USRP host driver.",
    domain: "dsp",
    id: "ettusresearch-uhd",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "uhd",
    owner: "EttusResearch",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
