import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const EMBEDDED_REPOS: Repository[] = [
  {
    description: "RTOS kernel.",
    domain: "embedded",
    id: "freertos-freertos-kernel",
    languages: ["C"],
    license: "MIT",
    maintenance: "active",
    name: "FreeRTOS-Kernel",
    owner: "FreeRTOS",
    resourceId: "freertos",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Full distribution with demos.",
    domain: "embedded",
    id: "freertos-freertos",
    languages: ["C"],
    license: "MIT",
    maintenance: "active",
    name: "FreeRTOS",
    owner: "FreeRTOS",
    resourceId: "freertos",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Zephyr RTOS.",
    domain: "embedded",
    id: "zephyrproject-rtos-zephyr",
    languages: ["C"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "zephyr",
    owner: "zephyrproject-rtos",
    resourceId: "zephyr",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Embedded emulation.",
    domain: "embedded",
    id: "renode-renode",
    languages: ["C#"],
    license: "MIT",
    maintenance: "active",
    name: "renode",
    owner: "renode",
    resourceId: "renode",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "ARM DSP library.",
    domain: "embedded",
    id: "arm-software-cmsis-dsp",
    languages: ["C"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "CMSIS-DSP",
    owner: "ARM-software",
    resourceId: "cmsis-dsp",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Cortex software interface standard.",
    domain: "embedded",
    id: "arm-software-cmsis-6",
    languages: ["C"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "CMSIS_6",
    note: "CMSIS_5, which drafts cite, is archived.",
    owner: "ARM-software",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "IoT RTOS.",
    domain: "embedded",
    id: "riot-os-riot",
    languages: ["C"],
    license: "LGPL-2.1",
    maintenance: "active",
    name: "RIOT",
    owner: "RIOT-OS",
    resourceId: "riot-os",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "POSIX RTOS.",
    domain: "embedded",
    id: "apache-nuttx",
    languages: ["C"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "nuttx",
    owner: "apache",
    resourceId: "nuttx",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Python on MCUs.",
    domain: "embedded",
    id: "micropython-micropython",
    languages: ["C"],
    license: "MIT",
    maintenance: "active",
    name: "micropython",
    owner: "micropython",
    resourceId: "micropython",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Embedded build system.",
    domain: "embedded",
    id: "platformio-platformio-core",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "platformio-core",
    owner: "platformio",
    resourceId: "platformio",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "ESP32 framework.",
    domain: "embedded",
    id: "espressif-esp-idf",
    languages: ["C"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "esp-idf",
    owner: "espressif",
    resourceId: "esp-idf",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Scripted Arduino builds.",
    domain: "embedded",
    id: "arduino-arduino-cli",
    languages: ["Go"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "arduino-cli",
    owner: "arduino",
    resourceId: "arduino-cli",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Cortex-M firmware library.",
    domain: "embedded",
    id: "libopencm3-libopencm3",
    languages: ["C"],
    license: "LGPL-3.0",
    maintenance: "steady",
    name: "libopencm3",
    owner: "libopencm3",
    resourceId: "libopencm3",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Debug and flash for Cortex-M.",
    domain: "embedded",
    id: "pyocd-pyocd",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "pyOCD",
    owner: "pyocd",
    resourceId: "pyocd",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Protocol decoding GUI.",
    domain: "embedded",
    id: "sigrokproject-pulseview",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "steady",
    name: "pulseview",
    owner: "sigrokproject",
    resourceId: "sigrok-pulseview",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "On-chip debug.",
    domain: "embedded",
    id: "openocd-org-openocd",
    languages: ["C"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "openocd",
    note: "GitHub mirror; drafts cite a Raspberry Pi fork.",
    owner: "openocd-org",
    resourceId: "openocd",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Wokwi simulator components.",
    domain: "embedded",
    id: "wokwi-wokwi-elements",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "wokwi-elements",
    owner: "wokwi",
    resourceId: "wokwi",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Machine emulator.",
    domain: "embedded",
    id: "qemu-qemu",
    languages: ["C"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "qemu",
    note: "GitHub mirror of the QEMU GitLab.",
    owner: "qemu",
    resourceId: "qemu",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "KiCad source.",
    domain: "embedded",
    id: "kicad-kicad-source-mirror",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "kicad-source-mirror",
    note: "GitHub mirror of the KiCad GitLab.",
    owner: "KiCad",
    resourceId: "kicad",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
