import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const INTEGRITY_REPOS: Repository[] = [
  {
    description: "Structural source code similarity.",
    domain: "integrity",
    id: "jplag-jplag",
    languages: ["Java"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "JPlag",
    owner: "jplag",
    resourceId: "jplag",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Source code plagiarism detection.",
    domain: "integrity",
    id: "dodona-edu-dolos",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "dolos",
    owner: "dodona-edu",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "FAIR metadata score for a repository.",
    domain: "integrity",
    id: "fair-software-howfairis",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "steady",
    name: "howfairis",
    owner: "fair-software",
    resourceId: "howfairis",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "The Zenodo platform.",
    domain: "integrity",
    id: "zenodo-zenodo",
    languages: ["Python"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "zenodo",
    owner: "zenodo",
    resourceId: "zenodo",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "The OSF backend.",
    domain: "integrity",
    id: "centerforopenscience-osf-io",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "osf.io",
    owner: "CenterForOpenScience",
    resourceId: "osf",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "PII detection and anonymisation.",
    domain: "integrity",
    id: "microsoft-presidio",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "presidio",
    owner: "microsoft",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Machine-generated text detection, research code.",
    domain: "integrity",
    id: "eric-mitchell-detect-gpt",
    languages: ["Python"],
    license: "MIT",
    maintenance: "archived",
    name: "detect-gpt",
    note: "Research artefact, not a tool.",
    owner: "eric-mitchell",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "The ORCID registry source.",
    domain: "integrity",
    id: "orcid-orcid-source",
    languages: ["Java"],
    license: "MIT",
    maintenance: "active",
    name: "ORCID-Source",
    owner: "ORCID",
    resourceId: "orcid",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
