import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const MATH_REPOS: Repository[] = [
  {
    description: "Graph algorithms.",
    domain: "math",
    id: "networkx-networkx",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "networkx",
    owner: "networkx",
    resourceId: "networkx",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Linear programming modeller.",
    domain: "math",
    id: "coin-or-pulp",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "pulp",
    owner: "coin-or",
    resourceId: "pulp",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Algebraic modelling.",
    domain: "math",
    id: "pyomo-pyomo",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "pyomo",
    owner: "Pyomo",
    resourceId: "pyomo",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Convex optimisation.",
    domain: "math",
    id: "cvxpy-cvxpy",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "cvxpy",
    owner: "cvxpy",
    resourceId: "cvxpy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Combinatorial optimisation.",
    domain: "math",
    id: "google-or-tools",
    languages: ["C++"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "or-tools",
    owner: "google",
    resourceId: "or-tools",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "LP and MIP solver.",
    domain: "math",
    id: "ergo-code-highs",
    languages: ["C++"],
    license: "MIT",
    maintenance: "active",
    name: "HiGHS",
    owner: "ERGO-Code",
    resourceId: "highs",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Hidden Markov models.",
    domain: "math",
    id: "hmmlearn-hmmlearn",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "steady",
    name: "hmmlearn",
    owner: "hmmlearn",
    resourceId: "hmmlearn",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Computer algebra system.",
    domain: "math",
    id: "sagemath-sage",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "sage",
    owner: "sagemath",
    resourceId: "sagemath",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Fast graph analysis.",
    domain: "math",
    id: "igraph-igraph",
    languages: ["C"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "igraph",
    owner: "igraph",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Discrete-event simulation.",
    domain: "math",
    id: "salabim-salabim",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "salabim",
    owner: "salabim",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
