import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const ML_REPOS: Repository[] = [
  {
    description: "Classical machine learning.",
    domain: "ml",
    id: "scikit-learn-scikit-learn",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "scikit-learn",
    owner: "scikit-learn",
    resourceId: "scikit-learn",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Deep learning framework.",
    domain: "ml",
    id: "pytorch-pytorch",
    languages: ["Python", "C++"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "pytorch",
    owner: "pytorch",
    resourceId: "pytorch",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Deep learning framework.",
    domain: "ml",
    id: "tensorflow-tensorflow",
    languages: ["Python", "C++"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "tensorflow",
    owner: "tensorflow",
    resourceId: "tensorflow",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "High-level API over JAX, PyTorch, and TensorFlow.",
    domain: "ml",
    id: "keras-team-keras",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "keras",
    owner: "keras-team",
    resourceId: "tensorflow",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Training loop scaffolding.",
    domain: "ml",
    id: "lightning-ai-pytorch-lightning",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "pytorch-lightning",
    owner: "Lightning-AI",
    resourceId: "pytorch-lightning",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Pretrained models.",
    domain: "ml",
    id: "huggingface-transformers",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "transformers",
    owner: "huggingface",
    resourceId: "hugging-face",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Dataset loading scripts.",
    domain: "ml",
    id: "huggingface-datasets",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "datasets",
    owner: "huggingface",
    resourceId: "hugging-face",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Feature attribution.",
    domain: "ml",
    id: "shap-shap",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "shap",
    note: "Moved from slundberg/shap.",
    owner: "shap",
    resourceId: "shap",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Attribution for PyTorch.",
    domain: "ml",
    id: "pytorch-captum",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "captum",
    owner: "pytorch",
    resourceId: "captum",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Model interchange format.",
    domain: "ml",
    id: "onnx-onnx",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "onnx",
    owner: "onnx",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Model graph visualiser.",
    domain: "ml",
    id: "lutzroeder-netron",
    languages: ["JavaScript"],
    license: "MIT",
    maintenance: "active",
    name: "netron",
    owner: "lutzroeder",
    resourceId: "netron",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Resampling for skewed classes.",
    domain: "ml",
    id: "scikit-learn-contrib-imbalanced-learn",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "imbalanced-learn",
    owner: "scikit-learn-contrib",
    resourceId: "imbalanced-learn",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Visual model diagnostics.",
    domain: "ml",
    id: "districtdatalabs-yellowbrick",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "steady",
    name: "yellowbrick",
    owner: "DistrictDataLabs",
    resourceId: "yellowbrick",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Distributed training and tuning.",
    domain: "ml",
    id: "ray-project-ray",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "ray",
    owner: "ray-project",
    resourceId: "ray",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Gradient boosting.",
    domain: "ml",
    id: "dmlc-xgboost",
    languages: ["C++"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "xgboost",
    owner: "dmlc",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Fast boosting for tabular data.",
    domain: "ml",
    id: "microsoft-lightgbm",
    languages: ["C++"],
    license: "MIT",
    maintenance: "active",
    name: "LightGBM",
    owner: "microsoft",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Demo UI for a model.",
    domain: "ml",
    id: "gradio-app-gradio",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "gradio",
    owner: "gradio-app",
    resourceId: "gradio",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
