import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const MOBILE_CORE_REPOS: Repository[] = [
  {
    description: "5G NR gNodeB.",
    domain: "mobile-core",
    id: "srsran-srsran-project",
    languages: ["C++"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "srsRAN_Project",
    owner: "srsran",
    resourceId: "srsran",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "4G stack, still used for PHY teaching.",
    domain: "mobile-core",
    id: "srsran-srsran-4g",
    languages: ["C++"],
    license: "AGPL-3.0",
    maintenance: "steady",
    name: "srsRAN_4G",
    owner: "srsran",
    resourceId: "srsran",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "5G core and 4G EPC.",
    domain: "mobile-core",
    id: "open5gs-open5gs",
    languages: ["C"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "open5gs",
    owner: "open5gs",
    resourceId: "open5gs",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "3GPP RAN and core.",
    domain: "mobile-core",
    id: "openairinterface-openairinterface5g",
    languages: ["C"],
    license: "custom",
    maintenance: "active",
    name: "openairinterface5g",
    note: "Mirror of the EURECOM GitLab; OAI Public License.",
    owner: "OPENAIRINTERFACE",
    resourceId: "openairinterface",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "5G UE and gNodeB simulator.",
    domain: "mobile-core",
    id: "aligungr-ueransim",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "steady",
    name: "UERANSIM",
    owner: "aligungr",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Mobile ad hoc network emulator.",
    domain: "mobile-core",
    id: "adjacentlink-emane",
    languages: ["C++"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "emane",
    owner: "adjacentlink",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "5G simulation on OMNeT++.",
    domain: "mobile-core",
    id: "unipisa-simu5g",
    languages: ["C++"],
    license: "LGPL-3.0",
    maintenance: "active",
    name: "Simu5G",
    note: "Owner to confirm.",
    owner: "Unipisa",
    resourceId: "simu5g",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
