import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const NETWORKING_REPOS: Repository[] = [
  {
    description: "The ns-3 simulator.",
    domain: "networking",
    id: "nsnam-ns-3-dev-git",
    languages: ["C++"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "ns-3-dev-git",
    note: "GitHub mirror of the nsnam GitLab.",
    owner: "nsnam",
    resourceId: "ns-3",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "SDN emulator.",
    domain: "networking",
    id: "mininet-mininet",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "dormant",
    name: "mininet",
    note: "Stable but slow-moving; Containernet and Mininet-WiFi are more active.",
    owner: "mininet",
    resourceId: "mininet",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Container-based Mininet.",
    domain: "networking",
    id: "containernet-containernet",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "steady",
    name: "containernet",
    owner: "containernet",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Wireless station emulation for Mininet.",
    domain: "networking",
    id: "intrig-unicamp-mininet-wifi",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "steady",
    name: "mininet-wifi",
    owner: "intrig-unicamp",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Declarative container topologies.",
    domain: "networking",
    id: "srl-labs-containerlab",
    languages: ["Go"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "containerlab",
    owner: "srl-labs",
    resourceId: "containerlab",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Lightweight topology emulation.",
    domain: "networking",
    id: "coreemu-core",
    languages: ["Python"],
    license: "BSD-2-Clause",
    maintenance: "active",
    name: "core",
    owner: "coreemu",
    resourceId: "core-emulator",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Routing suite.",
    domain: "networking",
    id: "frrouting-frr",
    languages: ["C"],
    license: "GPL-2.0-or-later",
    maintenance: "active",
    name: "frr",
    owner: "FRRouting",
    resourceId: "frrouting",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Routing daemon.",
    domain: "networking",
    id: "cz-nic-bird",
    languages: ["C"],
    license: "GPL-2.0-or-later",
    maintenance: "active",
    name: "bird",
    owner: "CZ-NIC",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Network configuration analysis.",
    domain: "networking",
    id: "batfish-batfish",
    languages: ["Java"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "batfish",
    owner: "batfish",
    resourceId: "batfish",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Bandwidth measurement.",
    domain: "networking",
    id: "esnet-iperf",
    languages: ["C"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "iperf",
    owner: "esnet",
    resourceId: "iperf3",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Command-line capture.",
    domain: "networking",
    id: "the-tcpdump-group-tcpdump",
    languages: ["C"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "tcpdump",
    owner: "the-tcpdump-group",
    resourceId: "tcpdump",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Packet crafting.",
    domain: "networking",
    id: "secdev-scapy",
    languages: ["Python"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "scapy",
    owner: "secdev",
    resourceId: "scapy",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Virtual switch.",
    domain: "networking",
    id: "openvswitch-ovs",
    languages: ["C"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "ovs",
    owner: "openvswitch",
    resourceId: "open-vswitch",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "P4 reference switch.",
    domain: "networking",
    id: "p4lang-behavioral-model",
    languages: ["C++"],
    license: "Apache-2.0",
    maintenance: "steady",
    name: "behavioral-model",
    owner: "p4lang",
    resourceId: "p4-bmv2",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "P4 compiler.",
    domain: "networking",
    id: "p4lang-p4c",
    languages: ["C++"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "p4c",
    owner: "p4lang",
    resourceId: "p4-bmv2",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "OpenFlow controller.",
    domain: "networking",
    id: "faucetsdn-ryu",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "dormant",
    name: "ryu",
    note: "Unmaintained upstream; forks carry fixes.",
    owner: "faucetsdn",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Analyzer source.",
    domain: "networking",
    id: "wireshark-wireshark",
    languages: ["C"],
    license: "GPL-2.0-or-later",
    maintenance: "active",
    name: "wireshark",
    note: "GitHub mirror of the Wireshark GitLab.",
    owner: "wireshark",
    resourceId: "wireshark",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "GNS3 interface.",
    domain: "networking",
    id: "gns3-gns3-gui",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "gns3-gui",
    owner: "GNS3",
    resourceId: "gns3",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "GNS3 backend.",
    domain: "networking",
    id: "gns3-gns3-server",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "gns3-server",
    owner: "GNS3",
    resourceId: "gns3",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Replay captured traffic.",
    domain: "networking",
    id: "appneta-tcpreplay",
    languages: ["C"],
    license: "GPL-3.0",
    maintenance: "steady",
    name: "tcpreplay",
    owner: "appneta",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Media framework.",
    domain: "networking",
    id: "ffmpeg-ffmpeg",
    languages: ["C"],
    license: "LGPL-2.1",
    maintenance: "active",
    name: "FFmpeg",
    note: "GPL when built with GPL components.",
    owner: "FFmpeg",
    resourceId: "ffmpeg",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "MP4 and DASH packaging.",
    domain: "networking",
    id: "gpac-gpac",
    languages: ["C"],
    license: "LGPL-2.1",
    maintenance: "active",
    name: "gpac",
    owner: "gpac",
    resourceId: "gpac",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "VLC source.",
    domain: "networking",
    id: "videolan-vlc",
    languages: ["C"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "vlc",
    note: "GitHub mirror of the VideoLAN GitLab.",
    owner: "videolan",
    resourceId: "vlc",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Media metadata.",
    domain: "networking",
    id: "mediaarea-mediainfo",
    languages: ["C++"],
    license: "BSD-2-Clause",
    maintenance: "active",
    name: "MediaInfo",
    owner: "MediaArea",
    resourceId: "mediainfo",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Perceptual video quality.",
    domain: "networking",
    id: "netflix-vmaf",
    languages: ["Python", "C"],
    license: "BSD-2-Clause-Patent",
    maintenance: "active",
    name: "vmaf",
    owner: "Netflix",
    resourceId: "vmaf",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "DASH and HLS packaging.",
    domain: "networking",
    id: "shaka-project-shaka-packager",
    languages: ["C++"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "shaka-packager",
    owner: "shaka-project",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Reference DASH player.",
    domain: "networking",
    id: "dash-industry-forum-dash-js",
    languages: ["JavaScript"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "dash.js",
    owner: "Dash-Industry-Forum",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Browser HLS playback.",
    domain: "networking",
    id: "video-dev-hls-js",
    languages: ["TypeScript"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "hls.js",
    owner: "video-dev",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "MP4 and DASH inspection.",
    domain: "networking",
    id: "axiomatic-systems-bento4",
    languages: ["C++"],
    license: "GPL-2.0",
    maintenance: "steady",
    name: "Bento4",
    owner: "axiomatic-systems",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Capture and recording.",
    domain: "networking",
    id: "obsproject-obs-studio",
    languages: ["C"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "obs-studio",
    owner: "obsproject",
    resourceId: "obs-studio",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
