import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const RAG_AGENT_REPOS: Repository[] = [
  {
    description: "Cited question answering over local papers.",
    domain: "rag-agents",
    id: "future-house-paper-qa",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "paper-qa",
    owner: "Future-House",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Cited long-form topic reports.",
    domain: "rag-agents",
    id: "stanford-oval-storm",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "storm",
    owner: "stanford-oval",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Graph plus vector retrieval over documents.",
    domain: "rag-agents",
    id: "hkuds-lightrag",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "LightRAG",
    owner: "HKUDS",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Document RAG engine with a GUI.",
    domain: "rag-agents",
    id: "infiniflow-ragflow",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "ragflow",
    owner: "infiniflow",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Indexing layer for private research collections.",
    domain: "rag-agents",
    id: "run-llama-llama-index",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "llama_index",
    owner: "run-llama",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Search, QA, and RAG pipelines.",
    domain: "rag-agents",
    id: "deepset-ai-haystack",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "haystack",
    owner: "deepset-ai",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Autonomous research agent with cited reports.",
    domain: "rag-agents",
    id: "assafelovic-gpt-researcher",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "gpt-researcher",
    owner: "assafelovic",
    resourceId: "gpt-researcher",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Paper reading and LaTeX-aware review assistant.",
    domain: "rag-agents",
    id: "binary-husky-gpt-academic",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "gpt_academic",
    note: "Fast-moving; pin a commit and expect breakage.",
    owner: "binary-husky",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Self-hosted UI for local models.",
    domain: "rag-agents",
    id: "open-webui-open-webui",
    languages: ["Python"],
    license: "custom",
    maintenance: "active",
    name: "open-webui",
    note: "Licence changed over time and includes a branding clause; read it before a public demo.",
    owner: "open-webui",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
