import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const READING_REPOS: Repository[] = [
  {
    description: "Structured extraction from PDFs.",
    domain: "reading",
    id: "kermitt2-grobid",
    languages: ["Java"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "grobid",
    note: "Some drafts cite grobidOrg/grobid; kermitt2 is the canonical owner.",
    owner: "kermitt2",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Fast PDF parsing and rendering.",
    domain: "reading",
    id: "pymupdf-pymupdf",
    languages: ["Python"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "PyMuPDF",
    note: "AGPL: a script that uses it and is published must carry the same licence.",
    owner: "pymupdf",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Layout-aware PDF text extraction.",
    domain: "reading",
    id: "pdfminer-pdfminer-six",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "pdfminer.six",
    note: "The permissive substitute for PyMuPDF.",
    owner: "pdfminer",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "PDFs to a knowledge graph with gap detection.",
    domain: "reading",
    id: "jit-ease-literature-mapper",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "literature-mapper",
    note: "New in 2026.",
    owner: "Jit-EASE",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Documents to Markdown for pipelines.",
    domain: "reading",
    id: "lancedb-e2m",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "e2m",
    owner: "lancedb",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
