import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const REFERENCE_REPOS: Repository[] = [
  {
    description: "The Zotero desktop client.",
    domain: "references",
    id: "zotero-zotero",
    languages: ["JavaScript"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "zotero",
    owner: "zotero",
    resourceId: "zotero",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Stable keys and BibTeX export.",
    domain: "references",
    id: "retorquere-zotero-better-bibtex",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "zotero-better-bibtex",
    owner: "retorquere",
    resourceId: "zotero-better-bibtex",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "BibTeX-native manager.",
    domain: "references",
    id: "jabref-jabref",
    languages: ["Java"],
    license: "MIT",
    maintenance: "active",
    name: "jabref",
    owner: "JabRef",
    resourceId: "jabref",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Parse and validate .bib files.",
    domain: "references",
    id: "sciunto-org-python-bibtexparser",
    languages: ["Python"],
    license: "LGPL-3.0",
    maintenance: "active",
    name: "python-bibtexparser",
    owner: "sciunto-org",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Citation parsing and formatting.",
    domain: "references",
    id: "citation-js-citation-js",
    languages: ["JavaScript"],
    license: "MIT",
    maintenance: "active",
    name: "citation-js",
    owner: "citation-js",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "DOI fetch and check plugin.",
    domain: "references",
    id: "bwiernik-zotero-shortdoi",
    languages: ["JavaScript"],
    license: "MIT",
    maintenance: "steady",
    name: "zotero-shortdoi",
    owner: "bwiernik",
    resourceId: "zotero-shortdoi",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "The CSL style repository.",
    domain: "references",
    id: "citation-style-language-styles",
    languages: ["XML"],
    license: "CC-BY-SA-3.0",
    maintenance: "active",
    name: "styles",
    owner: "citation-style-language",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Clean and sort BibTeX.",
    domain: "references",
    id: "flamingtempura-bibtex-tidy",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "bibtex-tidy",
    owner: "FlamingTempura",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "CSL citation processor in JavaScript.",
    domain: "references",
    id: "juris-m-citeproc-js",
    languages: ["JavaScript"],
    license: "CPAL-1.0",
    maintenance: "steady",
    name: "citeproc-js",
    owner: "Juris-M",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
