import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const REPRODUCIBILITY_REPOS: Repository[] = [
  {
    description: "Data and model versioning beside Git.",
    domain: "reproducibility",
    id: "iterative-dvc",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "dvc",
    owner: "iterative",
    resourceId: "dvc",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Experiment tracking and model registry.",
    domain: "reproducibility",
    id: "mlflow-mlflow",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "mlflow",
    owner: "mlflow",
    resourceId: "mlflow",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Self-hosted run comparison.",
    domain: "reproducibility",
    id: "aimhubio-aim",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "aim",
    owner: "aimhubio",
    resourceId: "aim",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Hyperparameter search with pruning.",
    domain: "reproducibility",
    id: "optuna-optuna",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "optuna",
    owner: "optuna",
    resourceId: "optuna",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Experiment configuration as files.",
    domain: "reproducibility",
    id: "facebookresearch-hydra",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "hydra",
    owner: "facebookresearch",
    resourceId: "hydra",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Pipelines as a rerunnable DAG.",
    domain: "reproducibility",
    id: "snakemake-snakemake",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "snakemake",
    owner: "snakemake",
    resourceId: "snakemake",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Fast conda-compatible solver.",
    domain: "reproducibility",
    id: "mamba-org-mamba",
    languages: ["C++"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "mamba",
    owner: "mamba-org",
    resourceId: "miniforge",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Minimal conda-forge distribution.",
    domain: "reproducibility",
    id: "conda-forge-miniforge",
    languages: ["Shell"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "miniforge",
    owner: "conda-forge",
    resourceId: "miniforge",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Environment lock for Python plus system deps.",
    domain: "reproducibility",
    id: "prefix-dev-pixi",
    languages: ["Rust"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "pixi",
    owner: "prefix-dev",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Experiment metrics as PR comments.",
    domain: "reproducibility",
    id: "iterative-cml",
    languages: ["JavaScript"],
    license: "Apache-2.0",
    maintenance: "steady",
    name: "cml",
    owner: "iterative",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Dependency management with lockfiles.",
    domain: "reproducibility",
    id: "python-poetry-poetry",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "poetry",
    owner: "python-poetry",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Checks before every commit.",
    domain: "reproducibility",
    id: "pre-commit-pre-commit",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "pre-commit",
    owner: "pre-commit",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
