import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const REVIEW_REPOS: Repository[] = [
  {
    description: "Active-learning screening.",
    domain: "review",
    id: "asreview-asreview",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "asreview",
    owner: "asreview",
    resourceId: "asreview",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Docker review workbench with PRISMA output.",
    domain: "review",
    id: "philipphaindl-reviq",
    languages: ["Python"],
    license: "custom",
    maintenance: "active",
    name: "ReviQ",
    note: "New in 2026; licence to confirm.",
    owner: "philipphaindl",
    resourceId: "reviq",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Git-native review environment.",
    domain: "review",
    id: "colrev-environment-colrev",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "colrev",
    owner: "CoLRev-Environment",
    resourceId: "colrev",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Multi-reviewer screening platform.",
    domain: "review",
    id: "geodes-sms-relis",
    languages: ["Python"],
    license: "AGPL-3.0",
    maintenance: "steady",
    name: "relis",
    owner: "geodes-sms",
    resourceId: "relis",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "PRISMA 2020 and MMAT toolkit with CLI.",
    domain: "review",
    id: "proportione-prisma",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "prisma",
    note: "New in 2026.",
    owner: "Proportione",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Desktop title and abstract screening.",
    domain: "review",
    id: "lars-ulaval-metascreener",
    languages: ["Python"],
    license: "custom",
    maintenance: "active",
    name: "metaScreener",
    note: "New in 2026; licence to confirm.",
    owner: "lars-ulaval",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "AI-assisted protocol reviews.",
    domain: "review",
    id: "open-and-sustainable-prismaid",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "prismAId",
    note: "New in 2026.",
    owner: "Open-and-Sustainable",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Review tool with Crossref snowballing.",
    domain: "review",
    id: "thoth2023-thoth-remake",
    languages: ["PHP"],
    license: "custom",
    maintenance: "steady",
    name: "thoth-remake",
    note: "Owner to confirm.",
    owner: "Thoth2023",
    resourceId: "thoth",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Bibliometric analysis of a paper set.",
    domain: "review",
    id: "nlesc-litstudy",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "steady",
    name: "litstudy",
    owner: "NLeSC",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Science mapping in R.",
    domain: "review",
    id: "massimoaria-bibliometrix",
    languages: ["R"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "bibliometrix",
    owner: "massimoaria",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Screening and organising bibliographic data in R.",
    domain: "review",
    id: "mjwestgate-revtools",
    languages: ["R"],
    license: "GPL-3.0",
    maintenance: "dormant",
    name: "revtools",
    owner: "mjwestgate",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
