import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const SATELLITE_REPOS: Repository[] = [
  {
    description: "Link budgets and propagation.",
    domain: "satellite",
    id: "jman4162-opensatcom",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "opensatcom",
    owner: "jman4162",
    resourceId: "opensatcom",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Ephemeris and pass prediction.",
    domain: "satellite",
    id: "skyfielders-python-skyfield",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "python-skyfield",
    owner: "skyfielders",
    resourceId: "skyfield",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "SGP4 propagator.",
    domain: "satellite",
    id: "brandon-rhodes-python-sgp4",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "python-sgp4",
    owner: "brandon-rhodes",
    resourceId: "python-sgp4",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Coordinates, time, units.",
    domain: "satellite",
    id: "astropy-astropy",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "astropy",
    owner: "astropy",
    resourceId: "astropy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Tracking application.",
    domain: "satellite",
    id: "csete-gpredict",
    languages: ["C"],
    license: "GPL-2.0",
    maintenance: "steady",
    name: "gpredict",
    owner: "csete",
    resourceId: "gpredict",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Ground station client.",
    domain: "satellite",
    id: "satnogs-satnogs-client",
    languages: ["Python"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "satnogs-client",
    owner: "satnogs",
    resourceId: "satnogs",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Network coordination backend.",
    domain: "satellite",
    id: "satnogs-satnogs-network",
    languages: ["Python"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "satnogs-network",
    owner: "satnogs",
    resourceId: "satnogs",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Telemetry decoders.",
    domain: "satellite",
    id: "daniestevez-gr-satellites",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "gr-satellites",
    owner: "daniestevez",
    resourceId: "gr-satellites",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Downlink decoder suite.",
    domain: "satellite",
    id: "satdump-satdump",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "SatDump",
    owner: "SatDump",
    resourceId: "satdump",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Core Flight System.",
    domain: "satellite",
    id: "nasa-cfs",
    languages: ["C"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "cFS",
    owner: "nasa",
    resourceId: "nasa-cfs",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Orbital mechanics, maintenance mode.",
    domain: "satellite",
    id: "poliastro-poliastro",
    languages: ["Python"],
    license: "MIT",
    maintenance: "dormant",
    name: "poliastro",
    note: "Fine for coursework; consider nyx for a thesis core.",
    owner: "poliastro",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Rust astrodynamics.",
    domain: "satellite",
    id: "nyx-space-nyx",
    languages: ["Rust"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "nyx",
    owner: "nyx-space",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Orbital parameters from TLE.",
    domain: "satellite",
    id: "pytroll-pyorbital",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "pyorbital",
    owner: "pytroll",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Satellite imagery readers.",
    domain: "satellite",
    id: "pytroll-satpy",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "satpy",
    owner: "pytroll",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
