import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const SCHOLARLY_API_REPOS: Repository[] = [
  {
    description: "Google Scholar metadata from Python.",
    domain: "scholarly-apis",
    id: "scholarly-python-package-scholarly",
    languages: ["Python"],
    license: "Unlicense",
    maintenance: "steady",
    name: "scholarly",
    note: "Scraping Scholar is rate-limited; prefer the OpenAlex and Crossref APIs.",
    owner: "scholarly-python-package",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Semantic Scholar API client.",
    domain: "scholarly-apis",
    id: "danielnsilva-semanticscholar",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "semanticscholar",
    owner: "danielnsilva",
    resourceId: "semantic-scholar",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "OpenAlex API docs and examples.",
    domain: "scholarly-apis",
    id: "ourresearch-openalex-api",
    languages: ["Jupyter"],
    license: "MIT",
    maintenance: "active",
    name: "openalex-api",
    note: "Repository name to confirm.",
    owner: "ourresearch",
    resourceId: "openalex",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Crossref REST client.",
    domain: "scholarly-apis",
    id: "fabiobatalha-crossrefapi",
    languages: ["Python"],
    license: "BSD-2-Clause",
    maintenance: "dormant",
    name: "crossrefapi",
    note: "Thin wrapper; calling the REST API directly removes the dependency.",
    owner: "fabiobatalha",
    resourceId: "crossref",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Self-hosted arXiv recommender.",
    domain: "scholarly-apis",
    id: "karpathy-arxiv-sanity-lite",
    languages: ["Python"],
    license: "MIT",
    maintenance: "dormant",
    name: "arxiv-sanity-lite",
    note: "Personal project; use as a reference for ranking logic.",
    owner: "karpathy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Curated classic papers.",
    domain: "scholarly-apis",
    id: "papers-we-love-papers-we-love",
    languages: ["Markdown"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "papers-we-love",
    owner: "papers-we-love",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Bulk PDF acquisition utilities.",
    domain: "scholarly-apis",
    id: "allenai-paper-scraper",
    languages: ["Python"],
    license: "custom",
    maintenance: "unverified",
    name: "paper-scraper",
    note: "Repository to confirm.",
    owner: "allenai",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
