import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const SECURITY_REPOS: Repository[] = [
  {
    description: "Data and crypto workbench.",
    domain: "security",
    id: "gchq-cyberchef",
    languages: ["JavaScript"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "CyberChef",
    owner: "gchq",
    resourceId: "cyberchef",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "TLS and primitives.",
    domain: "security",
    id: "openssl-openssl",
    languages: ["C"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "openssl",
    owner: "openssl",
    resourceId: "openssl",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Python primitives.",
    domain: "security",
    id: "pyca-cryptography",
    languages: ["Python", "Rust"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "cryptography",
    note: "Dual Apache-2.0 or BSD-3-Clause.",
    owner: "pyca",
    resourceId: "pyca-cryptography",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Misuse-resistant crypto.",
    domain: "security",
    id: "jedisct1-libsodium",
    languages: ["C"],
    license: "ISC",
    maintenance: "active",
    name: "libsodium",
    owner: "jedisct1",
    resourceId: "libsodium",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Post-quantum algorithms.",
    domain: "security",
    id: "open-quantum-safe-liboqs",
    languages: ["C"],
    license: "MIT",
    maintenance: "active",
    name: "liboqs",
    owner: "open-quantum-safe",
    resourceId: "liboqs",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Self-contained Python crypto.",
    domain: "security",
    id: "legrandin-pycryptodome",
    languages: ["Python"],
    license: "BSD-2-Clause",
    maintenance: "active",
    name: "pycryptodome",
    owner: "Legrandin",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Hash auditing.",
    domain: "security",
    id: "hashcat-hashcat",
    languages: ["C"],
    license: "MIT",
    maintenance: "active",
    name: "hashcat",
    owner: "hashcat",
    resourceId: "hashcat",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Password auditing.",
    domain: "security",
    id: "openwall-john",
    languages: ["C"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "john",
    owner: "openwall",
    resourceId: "john-the-ripper",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Reverse engineering.",
    domain: "security",
    id: "nationalsecurityagency-ghidra",
    languages: ["Java"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "ghidra",
    owner: "NationalSecurityAgency",
    resourceId: "ghidra",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Reverse engineering framework.",
    domain: "security",
    id: "radareorg-radare2",
    languages: ["C"],
    license: "LGPL-3.0",
    maintenance: "active",
    name: "radare2",
    owner: "radareorg",
    resourceId: "radare2",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Exploit development.",
    domain: "security",
    id: "gallopsled-pwntools",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "pwntools",
    owner: "Gallopsled",
    resourceId: "pwntools",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Network security monitor.",
    domain: "security",
    id: "zeek-zeek",
    languages: ["C++"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "zeek",
    owner: "zeek",
    resourceId: "zeek",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "IDS and IPS.",
    domain: "security",
    id: "oisf-suricata",
    languages: ["C", "Rust"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "suricata",
    owner: "OISF",
    resourceId: "suricata",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "SIEM and XDR.",
    domain: "security",
    id: "wazuh-wazuh",
    languages: ["C", "Python"],
    license: "GPL-2.0",
    maintenance: "active",
    name: "wazuh",
    owner: "wazuh",
    resourceId: "wazuh",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Web scanner.",
    domain: "security",
    id: "zaproxy-zaproxy",
    languages: ["Java"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "zaproxy",
    owner: "zaproxy",
    resourceId: "owasp-zap",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Static analysis.",
    domain: "security",
    id: "semgrep-semgrep",
    languages: ["OCaml", "Python"],
    license: "LGPL-2.1",
    maintenance: "active",
    name: "semgrep",
    owner: "semgrep",
    resourceId: "semgrep",
    reuseClass: "weak-copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Vulnerability scanning.",
    domain: "security",
    id: "aquasecurity-trivy",
    languages: ["Go"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "trivy",
    owner: "aquasecurity",
    resourceId: "trivy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Secret scanning.",
    domain: "security",
    id: "gitleaks-gitleaks",
    languages: ["Go"],
    license: "MIT",
    maintenance: "active",
    name: "gitleaks",
    owner: "gitleaks",
    resourceId: "gitleaks",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Identity and access.",
    domain: "security",
    id: "keycloak-keycloak",
    languages: ["Java"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "keycloak",
    owner: "keycloak",
    resourceId: "keycloak",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "HTTPS proxy.",
    domain: "security",
    id: "mitmproxy-mitmproxy",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "mitmproxy",
    owner: "mitmproxy",
    resourceId: "mitmproxy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Penetration testing framework.",
    domain: "security",
    id: "rapid7-metasploit-framework",
    languages: ["Ruby"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "metasploit-framework",
    owner: "rapid7",
    resourceId: "metasploit",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Malware pattern matching.",
    domain: "security",
    id: "virustotal-yara",
    languages: ["C"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "yara",
    owner: "VirusTotal",
    resourceId: "yara",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Discovery scanner.",
    domain: "security",
    id: "nmap-nmap",
    languages: ["C++"],
    license: "custom",
    maintenance: "active",
    name: "nmap",
    note: "Nmap Public Source License, not OSI approved.",
    owner: "nmap",
    resourceId: "nmap",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "RSA attack collection for teaching.",
    domain: "security",
    id: "rsactftool-rsactftool",
    languages: ["Python"],
    license: "custom",
    maintenance: "active",
    name: "RsaCtfTool",
    note: "Licence to confirm.",
    owner: "RsaCtfTool",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Web security testing guide source.",
    domain: "security",
    id: "owasp-wstg",
    languages: ["Markdown"],
    license: "CC-BY-SA-4.0",
    maintenance: "active",
    name: "wstg",
    owner: "OWASP",
    resourceId: "owasp",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "WAF rules for common web attacks.",
    domain: "security",
    id: "coreruleset-coreruleset",
    languages: ["Other"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "coreruleset",
    owner: "coreruleset",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Code analysis platform.",
    domain: "security",
    id: "github-codeql",
    languages: ["QL"],
    license: "MIT",
    maintenance: "active",
    name: "codeql",
    owner: "github",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
