import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const TEMPLATE_REPOS: Repository[] = [
  {
    description: "Typst thesis scaffold.",
    domain: "templates",
    id: "splines-typst-thesis-starter",
    languages: ["Typst"],
    license: "Unlicense",
    maintenance: "steady",
    name: "typst-thesis-starter",
    owner: "Splines",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Dissertation template in Typst and Quarto.",
    domain: "templates",
    id: "stanfordhpds-typst-stanford-thesis",
    languages: ["Typst"],
    license: "MIT",
    maintenance: "steady",
    name: "typst-stanford-thesis",
    owner: "StanfordHPDS",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "LaTeX template serving many schools.",
    domain: "templates",
    id: "joaomlourenco-novathesis",
    languages: ["TeX"],
    license: "LPPL-1.3c",
    maintenance: "active",
    name: "novathesis",
    owner: "joaomlourenco",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Thesis template with draft mode and build scripts.",
    domain: "templates",
    id: "ruedigervoigt-latex-thesis-template",
    languages: ["TeX"],
    license: "custom",
    maintenance: "steady",
    name: "LaTeX-Thesis-Template",
    owner: "RuedigerVoigt",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Minimal modern LaTeX thesis.",
    domain: "templates",
    id: "goethe-tcs-thesis-template",
    languages: ["TeX"],
    license: "MIT",
    maintenance: "steady",
    name: "thesis-template",
    owner: "goethe-tcs",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Thesis template with build automation.",
    domain: "templates",
    id: "ctu-mrs-thesis-template",
    languages: ["TeX"],
    license: "custom",
    maintenance: "steady",
    name: "thesis_template",
    owner: "ctu-mrs",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
