import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const VISION_REPOS: Repository[] = [
  {
    description: "Vision library.",
    domain: "vision",
    id: "opencv-opencv",
    languages: ["C++"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "opencv",
    owner: "opencv",
    resourceId: "opencv",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "NumPy image processing.",
    domain: "vision",
    id: "scikit-image-scikit-image",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "scikit-image",
    owner: "scikit-image",
    resourceId: "scikit-image",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Differentiable vision ops.",
    domain: "vision",
    id: "kornia-kornia",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "kornia",
    owner: "kornia",
    resourceId: "kornia",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Augmentation.",
    domain: "vision",
    id: "albumentations-team-albumentations",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "albumentations",
    owner: "albumentations-team",
    resourceId: "albumentations",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Multi-modal annotation.",
    domain: "vision",
    id: "humansignal-label-studio",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "label-studio",
    owner: "HumanSignal",
    resourceId: "label-studio",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Image and video annotation.",
    domain: "vision",
    id: "cvat-ai-cvat",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "cvat",
    owner: "cvat-ai",
    resourceId: "cvat",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Dataset curation.",
    domain: "vision",
    id: "voxel51-fiftyone",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "fiftyone",
    owner: "voxel51",
    resourceId: "fiftyone",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "YOLO models.",
    domain: "vision",
    id: "ultralytics-ultralytics",
    languages: ["Python"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "ultralytics",
    note: "A deployed derivative must publish its source or buy a commercial licence.",
    owner: "ultralytics",
    resourceId: "ultralytics-yolo",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Detection and segmentation.",
    domain: "vision",
    id: "facebookresearch-detectron2",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "steady",
    name: "detectron2",
    owner: "facebookresearch",
    resourceId: "detectron2",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Detection toolbox.",
    domain: "vision",
    id: "open-mmlab-mmdetection",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "steady",
    name: "mmdetection",
    owner: "open-mmlab",
    resourceId: "mmdetection",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Promptable segmentation.",
    domain: "vision",
    id: "facebookresearch-sam2",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "sam2",
    owner: "facebookresearch",
    resourceId: "segment-anything",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "3D geometry processing.",
    domain: "vision",
    id: "isl-org-open3d",
    languages: ["C++"],
    license: "MIT",
    maintenance: "active",
    name: "Open3D",
    owner: "isl-org",
    resourceId: "open3d",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Scientific image analysis.",
    domain: "vision",
    id: "imagej-imagej2",
    languages: ["Java"],
    license: "BSD-2-Clause",
    maintenance: "active",
    name: "imagej2",
    owner: "imagej",
    resourceId: "imagej-fiji",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Reference vision datasets and models.",
    domain: "vision",
    id: "pytorch-vision",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "active",
    name: "vision",
    owner: "pytorch",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Image loading and preprocessing.",
    domain: "vision",
    id: "python-pillow-pillow",
    languages: ["Python"],
    license: "MIT-CMU",
    maintenance: "active",
    name: "Pillow",
    owner: "python-pillow",
    resourceId: "pillow",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Detection result utilities.",
    domain: "vision",
    id: "roboflow-supervision",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "supervision",
    owner: "roboflow",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Browser annotation tool.",
    domain: "vision",
    id: "skalskip-make-sense",
    languages: ["TypeScript"],
    license: "GPL-3.0",
    maintenance: "steady",
    name: "make-sense",
    owner: "SkalskiP",
    resourceId: "make-sense",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Polygon annotation in Python.",
    domain: "vision",
    id: "wkentaro-labelme",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "labelme",
    note: "Some drafts cite a fork; wkentaro is the canonical owner.",
    owner: "wkentaro",
    resourceId: "labelme",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
