import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const WIRELESS_REPOS: Repository[] = [
  {
    description: "GPU link-level simulator.",
    domain: "wireless",
    id: "nvlabs-sionna",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "sionna",
    owner: "NVlabs",
    resourceId: "sionna",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Modulation, channels, and coding in Python.",
    domain: "wireless",
    id: "veeresht-commpy",
    languages: ["Python"],
    license: "BSD-3-Clause",
    maintenance: "dormant",
    name: "CommPy",
    note: "Slow-moving; fine for coursework scripts.",
    owner: "veeresht",
    resourceId: "commpy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Minimal comms chain.",
    domain: "wireless",
    id: "vincentchoqueuse-comnumpy",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "comnumpy",
    owner: "vincentchoqueuse",
    resourceId: "comnumpy",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "FEC toolbox.",
    domain: "wireless",
    id: "aff3ct-aff3ct",
    languages: ["C++"],
    license: "MIT",
    maintenance: "active",
    name: "aff3ct",
    owner: "aff3ct",
    resourceId: "aff3ct",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Learned communications in PyTorch.",
    domain: "wireless",
    id: "ipc-lab-kaira",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "kaira",
    owner: "ipc-lab",
    resourceId: "kaira",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Ray-traced channel datasets.",
    domain: "wireless",
    id: "deepmimo-deepmimo",
    languages: ["Python"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "DeepMIMO",
    owner: "DeepMIMO",
    resourceId: "deepmimo",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Synthetic RF datasets.",
    domain: "wireless",
    id: "torchdsp-torchsig",
    languages: ["Python"],
    license: "custom",
    maintenance: "active",
    name: "torchsig",
    note: "Licence to confirm.",
    owner: "TorchDSP",
    resourceId: "torchsig",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Modulation, codes, and channels in NumPy.",
    domain: "wireless",
    id: "rwnobrega-komm",
    languages: ["Python"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "komm",
    note: "Owner to confirm; one draft cites mitexleo/komm.",
    owner: "rwnobrega",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "SDR physical layer research framework.",
    domain: "wireless",
    id: "lkk688-rf-stream-phy",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "RF-Stream-PHY",
    note: "New in 2026.",
    owner: "lkk688",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
