import { CATALOG_VERIFIED_ON } from "@/config/resources/verified-on";
import type { Repository } from "@/lib/resources/types";

export const WRITING_REPOS: Repository[] = [
  {
    description: "Markdown slides for developers.",
    domain: "writing",
    id: "slidevjs-slidev",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "slidev",
    owner: "slidevjs",
    resourceId: "slidev",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "HTML presentation framework.",
    domain: "writing",
    id: "hakimel-reveal-js",
    languages: ["JavaScript"],
    license: "MIT",
    maintenance: "active",
    name: "reveal.js",
    owner: "hakimel",
    resourceId: "reveal-js",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Universal document converter with citations.",
    domain: "writing",
    id: "jgm-pandoc",
    languages: ["Haskell"],
    license: "GPL-2.0-or-later",
    maintenance: "active",
    name: "pandoc",
    owner: "jgm",
    resourceId: "pandoc",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Reproducible publishing from Markdown plus code.",
    domain: "writing",
    id: "quarto-dev-quarto-cli",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "quarto-cli",
    owner: "quarto-dev",
    resourceId: "quarto",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "The Typst compiler.",
    domain: "writing",
    id: "typst-typst",
    languages: ["Rust"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "typst",
    owner: "typst",
    resourceId: "typst",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Language server for Typst.",
    domain: "writing",
    id: "myriad-dreamin-tinymist",
    languages: ["Rust"],
    license: "Apache-2.0",
    maintenance: "active",
    name: "tinymist",
    owner: "Myriad-Dreamin",
    resourceId: "typst",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Desktop LaTeX editor.",
    domain: "writing",
    id: "texstudio-org-texstudio",
    languages: ["C++"],
    license: "GPL-3.0",
    maintenance: "active",
    name: "texstudio",
    owner: "texstudio-org",
    resourceId: "texstudio",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Lightweight LaTeX editor.",
    domain: "writing",
    id: "texworks-texworks",
    languages: ["C++"],
    license: "GPL-2.0-or-later",
    maintenance: "steady",
    name: "texworks",
    owner: "TeXworks",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "VS Code LaTeX extension.",
    domain: "writing",
    id: "james-yu-latex-workshop",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "LaTeX-Workshop",
    owner: "James-Yu",
    resourceId: "latex-workshop",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Markdown slide decks.",
    domain: "writing",
    id: "marp-team-marp",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "marp",
    owner: "marp-team",
    resourceId: "marp",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Git-based manuscripts with DOI citations.",
    domain: "writing",
    id: "manubot-manubot",
    languages: ["Python"],
    license: "BSD-2-Clause",
    maintenance: "steady",
    name: "manubot",
    note: "Owner to confirm; some drafts cite greenelab/manubot.",
    owner: "manubot",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Local-first LaTeX and Typst editor.",
    domain: "writing",
    id: "texlyre-texlyre",
    languages: ["TypeScript"],
    license: "AGPL-3.0",
    maintenance: "active",
    name: "texlyre",
    note: "New in 2026.",
    owner: "TeXlyre",
    resourceId: "texlyre",
    reuseClass: "copyleft",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Local-first writing workspace.",
    domain: "writing",
    id: "oleafly-oleafly",
    languages: ["TypeScript"],
    license: "custom",
    maintenance: "active",
    name: "Oleafly",
    note: "New in 2026; licence to confirm.",
    owner: "Oleafly",
    resourceId: "oleafly",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Self-hosted Overleaf alternative.",
    domain: "writing",
    id: "oaklight-tinyleaf",
    languages: ["Python"],
    license: "custom",
    maintenance: "active",
    name: "tinyleaf",
    note: "New in 2026; licence to confirm.",
    owner: "Oaklight",
    resourceId: "tinyleaf",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Browser LaTeX editor with WASM compile.",
    domain: "writing",
    id: "swimmingbrain-texbrain",
    languages: ["TypeScript"],
    license: "custom",
    maintenance: "active",
    name: "texbrain",
    note: "New in 2026; licence to confirm.",
    owner: "swimmingbrain",
    resourceId: "texbrain",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "LaTeX plus AI workspace.",
    domain: "writing",
    id: "opendcai-openprism",
    languages: ["TypeScript"],
    license: "MIT",
    maintenance: "active",
    name: "OpenPrism",
    note: "New in 2026.",
    owner: "OpenDCAI",
    resourceId: "openprism",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Collaborative self-hosted LaTeX.",
    domain: "writing",
    id: "stolucc-flowtex",
    languages: ["TypeScript"],
    license: "custom",
    maintenance: "active",
    name: "flowtex",
    note: "Single maintainer; evaluate before a timeline-critical thesis.",
    owner: "stolucc",
    resourceId: "flowtex",
    reuseClass: "check",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Section-by-section writing skill.",
    domain: "writing",
    id: "shiyangzheng-scholarly",
    languages: ["Markdown"],
    license: "MIT",
    maintenance: "active",
    name: "scholarly",
    note: "New in 2026.",
    owner: "ShiyangZheng",
    resourceId: "scholarly-writing-skill",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
  {
    description: "Multi-agent draft generator.",
    domain: "writing",
    id: "philioai-opendraft",
    languages: ["Python"],
    license: "MIT",
    maintenance: "active",
    name: "opendraft",
    note: "Owner to confirm; federicodeponte/opendraft may be a different project.",
    owner: "PhilioAI",
    resourceId: "opendraft",
    reuseClass: "permissive",
    verifiedOn: CATALOG_VERIFIED_ON,
  },
];
