/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GpaCalculatorRouteImport } from './routes/gpa-calculator'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PlanOfStudyRouteImport } from './routes/plan-of-study'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as BrowseFolderIdRouteImport } from './routes/browse.$folderId'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as CourseCodeRouteImport } from './routes/course.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaCalculatorRoute = GpaCalculatorRouteImport.update({
  id: '/gpa-calculator',
  path: '/gpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanOfStudyRoute = PlanOfStudyRouteImport.update({
  id: '/plan-of-study',
  path: '/plan-of-study',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseFolderIdRoute = BrowseFolderIdRouteImport.update({
  id: '/browse/$folderId',
  path: '/browse/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCodeRoute = CourseCodeRouteImport.update({
  id: '/course/$code',
  path: '/course/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/exams': typeof ExamsRoute
  '/faq': typeof FaqRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/legal': typeof LegalRoute
  '/plan-of-study': typeof PlanOfStudyRoute
  '/recent': typeof RecentRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/browse/$folderId': typeof BrowseFolderIdRoute
  '/course/$code': typeof CourseCodeRoute
  '/course/': typeof CourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/exams': typeof ExamsRoute
  '/faq': typeof FaqRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/legal': typeof LegalRoute
  '/plan-of-study': typeof PlanOfStudyRoute
  '/recent': typeof RecentRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/browse/$folderId': typeof BrowseFolderIdRoute
  '/course/$code': typeof CourseCodeRoute
  '/course': typeof CourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/exams': typeof ExamsRoute
  '/faq': typeof FaqRoute
  '/gpa-calculator': typeof GpaCalculatorRoute
  '/legal': typeof LegalRoute
  '/plan-of-study': typeof PlanOfStudyRoute
  '/recent': typeof RecentRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/browse/$folderId': typeof BrowseFolderIdRoute
  '/course/$code': typeof CourseCodeRoute
  '/course/': typeof CourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/exams'
    | '/faq'
    | '/gpa-calculator'
    | '/legal'
    | '/plan-of-study'
    | '/recent'
    | '/saved'
    | '/search'
    | '/sitemap'
    | '/browse/$folderId'
    | '/course/$code'
    | '/course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/exams'
    | '/faq'
    | '/gpa-calculator'
    | '/legal'
    | '/plan-of-study'
    | '/recent'
    | '/saved'
    | '/search'
    | '/sitemap'
    | '/browse/$folderId'
    | '/course/$code'
    | '/course'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/exams'
    | '/faq'
    | '/gpa-calculator'
    | '/legal'
    | '/plan-of-study'
    | '/recent'
    | '/saved'
    | '/search'
    | '/sitemap'
    | '/browse/$folderId'
    | '/course/$code'
    | '/course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  ExamsRoute: typeof ExamsRoute
  FaqRoute: typeof FaqRoute
  GpaCalculatorRoute: typeof GpaCalculatorRoute
  LegalRoute: typeof LegalRoute
  PlanOfStudyRoute: typeof PlanOfStudyRoute
  RecentRoute: typeof RecentRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SitemapRoute: typeof SitemapRoute
  BrowseFolderIdRoute: typeof BrowseFolderIdRoute
  CourseCodeRoute: typeof CourseCodeRoute
  CourseIndexRoute: typeof CourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa-calculator': {
      id: '/gpa-calculator'
      path: '/gpa-calculator'
      fullPath: '/gpa-calculator'
      preLoaderRoute: typeof GpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-of-study': {
      id: '/plan-of-study'
      path: '/plan-of-study'
      fullPath: '/plan-of-study'
      preLoaderRoute: typeof PlanOfStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$folderId': {
      id: '/browse/$folderId'
      path: '/browse/$folderId'
      fullPath: '/browse/$folderId'
      preLoaderRoute: typeof BrowseFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$code': {
      id: '/course/$code'
      path: '/course/$code'
      fullPath: '/course/$code'
      preLoaderRoute: typeof CourseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  ExamsRoute: ExamsRoute,
  FaqRoute: FaqRoute,
  GpaCalculatorRoute: GpaCalculatorRoute,
  LegalRoute: LegalRoute,
  PlanOfStudyRoute: PlanOfStudyRoute,
  RecentRoute: RecentRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SitemapRoute: SitemapRoute,
  BrowseFolderIdRoute: BrowseFolderIdRoute,
  CourseCodeRoute: CourseCodeRoute,
  CourseIndexRoute: CourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
